Description of unit_test_cmp
Home > eidors > tools > unit_test_cmp.m
unit_test_cmp
PURPOSE
UNIT_TEST_CMP: compare matrices in eidors output
SYNOPSIS
function res = unit_test_cmp(txt,a,b,tol)
DESCRIPTION
 UNIT_TEST_CMP: compare matrices in eidors output
 unit_test_cmp(txt,a,b,tol)
 if tol = -negative it is an expected fail
 if tol = -inf then expented fail with no tolerance
 if a==b print ok, otherwise print fail
 To run unit tests and keep statistics
   unit_test_cmp UNIT_TEST_FCN fun_name
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG eidors progress and status messages
eidors_debug EIDORS_DEBUG Global managment of debug flags
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
freq_filt FREQ_FILT: frequency filter data
left_divide [V] = LEFT_DIVIDE(E,I,tol,pp,V);
calc_noise_params params = GREIT_noise_params(imdl, homg_voltage, sig_voltage)
np_fwd_solve NP_FWD_SOLVE: data= np_fwd_solve(fwd_model, img)
distmat DISTMAT Distance matrix for a set of points
calc_colours [colours,scl_data]= calc_colours(img, set_value, do_colourbar)
calc_slices calc_slices (img, levels, clim) show slices at levels of an
img_point_mapper IMG_POINT_MAPPER - image values at points
level_model_slice LEVEL_MODEL_SLICE - level 3D points for slicing at z=0
mdl_slice_mapper MDL_SLICE_MAPPER: map pixels to FEM elements or nodes
eidors_readdata EIDORS readdata - read data files from various EIT equipment
eidors_saveimg EIDORS saveimg - save reconstructed image files in formats
sigmatome2_filter SIGMATOME2_FILTER: Hardware filter and stim_patterns for Sigmatome II device
calc_mesh_quality CALC_MESH_QUALITY Various measures of mesh quality.
crop_model CROP_MODEL: Crop away parts of a fem model
dm_2d_circ_pt_elecs DM_2D_CIRC_PT_ELECS: Create circle mesh (or radius 1) refined with electrodes
gmsh_mk_2d_model GMSH_MK_2D_MODEL create a 2D mesh with GMSH
gmsh_mk_fwd_model GMSH_MK_FWD_MODEL: create a fwd_model object from a Gmsh file
gmsh_read_mesh [srf,vtx,fc,bc,simp,edg,mat_ind,phys_names,entities] = gmsh_read_mesh(filename)
gmsh_write_mesh gmsh_read_mesh(mdl, [data,] outfile)
join_models JOIN_MODELS: Join two fmdl structures to create one
mat_idx_to_electrode MAT_IDX_TO_ELECTRODE: create electrodes from mat_idx values
fourier_fit FOURIER_FIT: use fourier series to interpolate onto a boundary
ng_mk_fwd_model NG_MK_FWD_MODEL: create a fwd_model object from a netgen vol file
ng_mk_geometric_models NG_MK_GEOMETRIC_MODELS: create geometric mesh models using Netgen. Body
ng_read_opt NG_READ_OPT Read Netgen's ng.opt
ng_write_opt NG_WRITE_OPT Write an ng.opt file in current directory
order_loop ORDER_LOOP Order a list of points on a loop
GREIT3D_distribution GREIT3D_distribution: create target distributions for 3D GREIT
add_noise ADD_NOISE: Add a given SNR to EIDORS data
analytic_2d_circle V = analytic_2d_circle(J, [s_h, s_i, b, a, angl])
calc_elem_current calc_elem_current: calculate current vector in each FEM element
calc_model_reduction calc_model_reduction: calculate the fields for a reduced model
convhulln_clean CONVHULLN_CLEAN: run convhulln and catch errors
elec_rearrange ELEC_REARRANGE: rearrange electrodes for given pattern
elem_dim ELEM_DIM: dimension of elements in space (are elements in 2D or 3D space)
elem_select ELEM_SELECT: select element fractions inside a function
fix_model FIX_MODEL: Add useful fields to a model
get_elem_volume GET_ELEM_VOLUME: VOL = get_elem_volume(fwd_model, map_node)
interp_mesh INTERP_MESH: calculate interpolation points onto mdl elements
linear_reorder [fwd_model] = linear_reorder(fwd_model,ccw)
mdl_dim MDL_DIM: dimension of model space (are nodes in 2D or 3D space)
merge_meshes MERGE_MESHES - merges two meshes based on common nodes
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
mk_analytic_c2f MK_ANALYTIC_C2F: create a mapping matrix from coarse to fine FEM
mk_approx_c2f MK_APPROX_C2F: create a mapping matrix from coarse to fine FEM
mk_c2f_circ_mapping MK_C2F_CIRC_MAPPING: create a mapping matrix from circles/spheres to FEM
mk_circ_tank MK_CIRC_TANK: make a cylindrical tank FEM geometry in 2D or 3D
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_geophysics_model imdl = mk_geophysics_model(str, ne, [option])
mk_grid_c2f MK_GRID_C2F - calculate a coarse2fine mapping for grid coarse models.
mk_image MK_IMAGE: create eidors image object
mk_stim_patterns MK_STIM_PATTERNS: create an EIDORS stimulation pattern structure
mk_tet_c2f MK_TET_C2F - calculate a coarse2fine mapping for two tet-based models.
mk_tri2tet_c2f MK_TRI2TET_C2F - coarse2fine mapping between tri-based and tet-based models
mk_tri_c2f MK_TRI_C2F - calculate a coarse2fine mapping for triangle-based models.
mono2stim MONO2SIM transform monopolar stimulation into another stim pattern
num_elecs NUM_ELECS: number of electrodes attached to model
num_elems NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
num_nodes NUM_NODES: number of elemnts in a (fwd or inv model or image)
point_in_tet POINT_IN_TET test for points contained in elements
uniquetol C = uniquetol(A,TOL): unique values in A using tolerance TOL.
reciprocity_idx RECIPROCITY_IDX: find indices of stim, meas pairs that are recirocal
remove_unused_nodes REMOVE_UNUSED_NODES: identify and remove unused nodes in model
simulate_movement SIMULATE_MOVEMENT simulate small conductivity perturbations
solve_RM_2Dslice SOLVE_RM_2DSLICE: cut slices out of a 3D model
stim_meas_list STIM_MEAS_LIST: mk stimulation pattern from list of electrodes
stim_pattern_geophys STIM_PATTERN_GEOPHYS: Create Geophysical Stimulation Patterns
tet_to_inequal [A,b]=tet_to_inequal(v)
uniquetol C = uniquetol(A,TOL): unique values in A using tolerance TOL.
calc_R_prior R = calc_R_prior(inv_model, varargin)
calc_RtR_prior RtR = calc_RtR_prior(inv_model)
calc_jacobian_bkgnd CALC_JACOBIAN_BKGND: calculate background image around
calc_transferimpedance CALC_TRANSFERIMPEDANCE: Calculates transfer impedance matrix
fem_1st_to_higher_order FEM_1ST_TO_HIGH_ORDER: Modify the FEM for high order FEM called as
find_boundary [srf, idx] = find_boundary(simp);
fwd_model_parameters FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order(fwd_model, image)
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
fwd_solve_2p5d_1st_order FWD_SOLVE_2P5D_1ST_ORDER: data= fwd_solve_2p5d_1st_order(img)
fwd_solve_apparent_resistivity fwd_solve_apparent_resistivity: fwd_solve output as apparent resistivity
fwd_solve_halfspace FWD_SOLVE_HALFSPACE: data = fwd_solve_halfspace(img)
fwd_solve_higher_order Solve for voltages (nodes/electrodes) for a forward model.
jacobian_adjoint JACOBIAN_ADJOINT: J= jacobian_adjoint(img)
jacobian_adjoint_2p5d_1st_order JACOBIAN_ADJOINT_2P5D: J= jacobian_adjoint_2p5d_1st_order(img)
jacobian_adjoint_higher_order Find the Jacobian associated with an image (and forward model)
jacobian_movement JACOBIAN_MOVEMENT Computes the Jacobian matrix for conductivity and
jacobian_movement_2p5d_1st_order JACOBIAN_MOVEMENT_2P5D: J = jacobian_movement_2p5d_1st_order(img)
jacobian_perturb JACOBIAN_PERTURB: J= jacobian_perturb(fwd_model, img)
system_mat_1st_order SYSTEM_MAT_1ST_ORDER: SS= system_mat_1st_order(fwd_model, img)
system_mat_2p5d_1st_order SYSTEM_MAT_2P5D_1ST_ORDER: 2.5D system matrix
system_mat_2p5d_fields SYSTEM_MAT_2P5D_FIELDS: fields (elem to nodes) fraction of system mat
system_mat_fields SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
system_mat_higher_order Assemble the total stiffness matrix : s_mat.E=At;
system_mat_instrument SYSTEM_MAT_INSTRUMENT:
update_system_mat_fields UPDATE_SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
get_img_data GET_IMG_DATA: get parameter data from eidors image object
inv_solve INV_SOLVE: calculate imag from an inv_model and data
GREIT_desired_img_FEMmesh GREIT_DESIRED_IMG_FEMmesh GREIT onto a FEM mesh
calc_TSVD_RM CALC_TSVD_RM: Calculated truncated Jacobian SVD reconstruction matrix
calc_noise_figure CALC_NOISE_FIGURE: calculate the noise amplification (NF) of an algorithm
inv_solve_cg function img= inv_solve_cg(inv_model, data1);
inv_solve_core INV_SOLVE_CORE Solver using a generic iterative algorithm
inv_solve_gn function img= inv_solve_gn(inv_model, data1);
meas_icov_rm_elecs MEAS_ICOV_RM_ELECS: remove electrodes from consideration
prior_covar PRIOR_COVAR image prior with distance-based interelement covar
prior_gaussian_HPF PRIOR_GAUSSIAN_HPF calculate image prior
prior_laplace PRIOR_LAPLACE calculate image prior
prior_laplace_old PRIOR_LAPLACE calculate image prior
test_2d_resistor Create 2D model of a cylindrical resistor
test_3d_resistor Create 3D model of a Rectangular resistor
eidors_cache EIDORS_CACHE Control eidors caching
eidors_default EIDORS_DEFAULT Default function handler.
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
vectorize_inverse vectorize_inverse: fast computation of 3x3 and 4x4 inverses
SUBFUNCTIONS
function do_unit_test
SOURCE CODE
function res = unit_test_cmp(txt,a,b,tol)
% UNIT_TEST_CMP: compare matrices in eidors output
% unit_test_cmp(txt,a,b,tol)
% if tol = -negative it is an expected fail
% if tol = -inf then expented fail with no tolerance
% if a==b print ok, otherwise print fail
%
% To run unit tests and keep statistics
%   unit_test_cmp UNIT_TEST_FCN fun_name
% License GPL v2 or v3: $Id: unit_test_cmp.m 6501 2022-12-30 14:22:04Z aadler $
persistent ntotal;
persistent test_start_time;
persistent npass;
if strcmp(txt,'RESET_COUNTER');
    ntotal=0; npass=0; test_start_time=cputime(); return;
end
if strcmp(txt,'SHOW_COUNTER');
  if ntotal == 0;
     eidors_msg('%s: pass %d/%d (t=%6.2fs)',a, ...
         npass, ntotal, cputime() - test_start_time, 0 );
  else
     eidors_msg('%s: pass %d/%d = %5.1f%% (t=%6.2fs)', a, ...
         npass, ntotal, 100*npass/ntotal, ...
         cputime() - test_start_time, 0 );
  end
  return;
end
if strcmp(txt,'UNIT_TEST_FCN');
  unit_test_cmp('RESET_COUNTER');
  feval(a,'UNIT_TEST');
  unit_test_cmp( 'SHOW_COUNTER',a);
  return
end
if strcmp(txt,'UNIT_TEST'); do_unit_test; return; end
if nargin < 4; tol = 0; end
if tol<0;
   expect_fail = 1;
   if tol==-inf; tol= 0; end
else
   expect_fail= 0;
end
tolstr='';
   fprintf('TEST: %20s = ',txt);
   ok='Fail';
   if (isnumeric(a) || islogical(a)) && ...
      (isnumeric(b) || islogical(b))
      sza = size(a); szb= size(b);
      eqsz= isequal( size(a), size(b));
      sza1 = all(sza==1); szb1 = all(szb==1);
      if ~eqsz && ~sza1 && ~szb1
         ok='Fail (size change)';
      elseif any(isnan(a(:)) ~= isnan(b(:)))
             ok='Fail (NaNs change)';
      else
         rel_err = full(max(abs(double(a(:))-double(b(:)))));
         if rel_err <= tol;
            ok='OK';
         end
         if abs(rel_err)>0
            tolstr= sprintf('(%1.3f x tol)', rel_err/tol);
         end
      end
   else
      if strcmp(eidors_var_id(a), eidors_var_id(b)); ok='OK';end
   end
   if expect_fail
      ok = 'OK (fail as expected)';
   end
   fprintf('%4s %s\n', ok, tolstr);
   if strcmp(ok(1:2),'OK');
      npass= npass+1;
   else
      if eidors_debug('query','unit_test_cmp:fail')
          keyboard % uncomment to debug
      end
   end
   ntotal= ntotal+1;
   if nargout>0
       res = strcmp(ok(1:2),'OK');
   end
function do_unit_test
   unit_test_cmp('Expect OK'  ,3,3);
   unit_test_cmp('Expect Fail',1,1.01, -inf);
   unit_test_cmp('Expect OK'  ,1,.99,.02);
   unit_test_cmp('Expect Fail',1,.99,-.002);
   a= rand(10); b = a;
   unit_test_cmp('Expect OK'  ,a,b);
   unit_test_cmp('Expect Fail',a,b+.001, -inf);
   unit_test_cmp('Expect OK  ',a,b+.001, .002);
   a(1,1) = NaN; b=a;
   unit_test_cmp('Expect OK'  ,a,b);
   unit_test_cmp('Expect Fail',a,b+.001, -inf);
   unit_test_cmp('Expect OK  ',a,b+.001, .002);
   unit_test_cmp('Expect Fail',a,'boo', -inf);
   unit_test_cmp('Expect OK','boo','boo');
   t.a= a; s.a=b;
   unit_test_cmp('Expect OK'  ,t,s);
   s2.b= b;
   unit_test_cmp('Expect Fail'  ,t,s2, -inf);
   unit_test_cmp('Expect Fail', ones(3,3), ones(3,3,3), -inf);
   unit_test_cmp('Expect Fail', ones(3,1), ones(1,3), -inf);
   unit_test_cmp('Expect OK'  ,3,[3,3,3,3]);
   unit_test_cmp('Expect OK'  ,3,[3,3,3,3]);