% Algorithm list $Id: get_list_of_algs.m 1619 2008-09-22 16:32:56Z aadler $
function algs= get_list_of_algs;

algs = {'GREIT_Sheffield_backproj', ...
        'GREIT_NOSER_ndiff', ...
        'GREIT_NOSER_diff', ...
        'GREIT_test_ndiff', ...
       };
