Description of fwd_model_parameters
Home > eidors > solvers > forward > fwd_model_parameters.m
fwd_model_parameters
PURPOSE
FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order(fwd_model, image)
SYNOPSIS
function param = fwd_model_parameters(fwd_model, opt)
DESCRIPTION
 FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order( fwd_model, image)
   Internal function to extract parameters from a fwd_model
   param.n_elem     => number of elements
   param.n_elec     => number of electrodes
   param.n_node     => number of nodes (vertices)
   param.n_stim     => number of current stimulation patterns
   param.n_elec     => number of electrodes
   param.n_dims     => dimentions (2= 2D, 3=3D)
   param.n_meas     => number of measurements (total)
   param.boundary   => FEM boundary
   param.NODE       => vertex matrix
   param.ELEM       => connection matrix
   param.QQ         => Current into each NODE (Neuman Boundary Conditions)
   param.VV         => Voltage driven into each NODE (Dirichlet BC - only where QQ is NaN)
   param.YY         => Output Admittance (1/Impedance) of each node current (for each value in QQ)
   param.VOLUME     => Volume (or area) of each element
   param.normalize  => difference measurements normalized?
   param.N2E        => Node to electrode converter
   param.v2meas     => Convert node voltages to measurements
 If the stimulation patterns has a 'interior_sources' field,
   the node current QQ, is set to this value for this stimulation.
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG eidors progress and status messages
mdl_normalize MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
mk_common_model MK_COMMON_MODEL: make common EIT models
sparse SPARSE Create sparse matrix (EIDORS overload).
find_boundary [srf, idx] = find_boundary(simp);
find_electrode_bdy FIND_ELECTRODE_BDY: find the boundary index area for electrode
fwd_model_parameters FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order(fwd_model, image)
eidors_cache EIDORS_CACHE Control eidors caching
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
left_divide [V] = LEFT_DIVIDE(E,I,tol,pp,V);
aa_fwd_parameters AA_FWD_PARAMETERS: data= aa_fwd_solve(fwd_model, image)
exponential_covar_prior EXPONENTIAL_COVAR_PRIOR image prior with exponential
cheating_2d code to simulate inverse crimes in EIT
eidors2d_demo1 EidorsDemo1 Demonstrates the use of 2D EIT Package with linear basis
show_fem_move SHOW_FEM_MOVE Plot EIT finite element model (FEM) and movement
show_slices_move SHOW_SLICES_MOVE Shows planar slices of a 3D FEM with movement vectors
calc_jacobian CALC_JACOBIAN: calculate jacobian from an inv_model
fwd_model_parameters FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order(fwd_model, image)
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
fwd_solve_2p5d_1st_order FWD_SOLVE_2P5D_1ST_ORDER: data= fwd_solve_2p5d_1st_order(img)
fwd_solve_halfspace FWD_SOLVE_HALFSPACE: data = fwd_solve_halfspace(img)
jacobian_adjoint JACOBIAN_ADJOINT: J= jacobian_adjoint(img)
jacobian_adjoint_2p5d_1st_order JACOBIAN_ADJOINT_2P5D: J= jacobian_adjoint_2p5d_1st_order(img)
jacobian_movement JACOBIAN_MOVEMENT Computes the Jacobian matrix for conductivity and
jacobian_movement_2p5d_1st_order JACOBIAN_MOVEMENT_2P5D: J = jacobian_movement_2p5d_1st_order(img)
jacobian_movement_halfspace JACOBIAN_MOVEMENT_PERTURB: J= jacobian_movement_perturb(img)
jacobian_movement_perturb JACOBIAN_MOVEMENT_PERTURB: J= jacobian_movement_perturb(img)
system_mat_2p5d_fields SYSTEM_MAT_2P5D_FIELDS: fields (elem to nodes) fraction of system mat
system_mat_fields SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
update_system_mat_fields UPDATE_SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
inv_solve_backproj INV_SOLVE_BACKPROJ inverse solver using backprojection
inv_solve_conj_grad INV_SOLVE_CONJ_GRAD inverse solver based on the CG
inv_solve_core INV_SOLVE_CORE Solver using a generic iterative algorithm
inv_solve_diff_kalman INV_SOLVE_DIFF_KALMAN inverse solver for difference EIT
prior_exponential_covar PRIOR_EXPONENTIAL_COVAR image prior with exponential
prior_laplace_old PRIOR_LAPLACE calculate image prior
prior_movement PRIOR_MOVEMENT calculate image prior
prior_time_smooth PRIOR_TIME_SMOOTH calculate image prior
SUBFUNCTIONS
function pp= calc_param(fwd_model, opt)
function v2meas = get_v2meas(n_elec,n_stim,stim)
function VOLUME = element_volume(NODE, ELEM, e, d)
function [N2E,cem_electrodes] = calculate_N2E(fwd_model, bdy, n_elec, n);
function [N2Ei,N2Ei_nodes,cem_electrodes]= N2Ei_from_nodes(
function [QQ, VV, n_meas] = calc_QQ_slow(N2E, stim, p)
function [QQ, VV, n_meas] = calc_QQ_fast(N2E, stim, p)
function do_unit_test
SOURCE CODE
function param = fwd_model_parameters(fwd_model, opt)
% FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order(fwd_model, image)
%   Internal function to extract parameters from a fwd_model
%   param.n_elem     => number of elements
%   param.n_elec     => number of electrodes
%   param.n_node     => number of nodes (vertices)
%   param.n_stim     => number of current stimulation patterns
%   param.n_elec     => number of electrodes
%   param.n_dims     => dimentions (2= 2D, 3=3D)
%   param.n_meas     => number of measurements (total)
%   param.boundary   => FEM boundary
%   param.NODE       => vertex matrix
%   param.ELEM       => connection matrix
%   param.QQ         => Current into each NODE (Neuman Boundary Conditions)
%   param.VV         => Voltage driven into each NODE (Dirichlet BC - only where QQ is NaN)
%   param.YY         => Output Admittance (1/Impedance) of each node current (for each value in QQ)
%   param.VOLUME     => Volume (or area) of each element
%   param.normalize  => difference measurements normalized?
%   param.N2E        => Node to electrode converter
%   param.v2meas     => Convert node voltages to measurements
%
% If the stimulation patterns has a 'interior_sources' field,
%   the node current QQ, is set to this value for this stimulation.
% (C) 2005 Andy Adler. License: GPL version 2 or version 3
% $Id: fwd_model_parameters.m 6473 2022-12-25 22:41:48Z aadler $
if ischar(fwd_model) && strcmp(fwd_model, 'UNIT_TEST'); do_unit_test; return; end
if nargin < 2
   opt.skip_VOLUME = 0;
else
   assert(ischar(opt),'opt must be a string');
   assert(strcmp(opt,'skip_VOLUME'),'opt can only be ''skip_VOLUME''');
   opt = struct;
   opt.skip_VOLUME = 1;
end
copt.fstr = 'fwd_model_parameters';
copt.log_level = 4;
param = eidors_cache(@calc_param,{fwd_model, opt},copt);
% perform actual parameter calculation
function pp= calc_param(fwd_model, opt)
pp.NODE= fwd_model.nodes';
pp.ELEM= fwd_model.elems';
n= size(pp.NODE,2);        %NODEs
d= size(pp.ELEM,1);        %dimentions+1
e= size(pp.ELEM,2);        %ELEMents
try
   p = length(fwd_model.stimulation );
catch
   p = 0;
end
try
   n_elec= length( fwd_model.electrode );
catch
   n_elec= 0;
   fwd_model.electrode = [];
end
if ~opt.skip_VOLUME
   copt.fstr = 'element_volume';
   copt.log_level = 4;
   pp.VOLUME= eidors_cache(@element_volume, {pp.NODE, pp.ELEM, e, d}, copt );
end
if isfield(fwd_model,'boundary')
    bdy = double( fwd_model.boundary ); % double because of stupid matlab bugs
else
    bdy = find_boundary(fwd_model.elems);
end
try %add system_mat_fields.CEM_boundary if it exists
   bdy = [bdy;fwd_model.system_mat_fields.CEM_boundary];
end
% Matrix to convert Nodes to Electrodes
% Complete electrode model for all electrodes
%  N2E = sparse(1:n_elec, n+ (1:n_elec), 1, n_elec, n+n_elec);
%  pp.QQ= sparse(n+n_elec,p);
copt.cache_obj = {fwd_model.nodes,fwd_model.elems,fwd_model.electrode};
copt.fstr = 'calculate_N2E';
[N2E,cem_electrodes] = eidors_cache(@calculate_N2E,{fwd_model, bdy, n_elec, n}, copt);
% pack into a parameter return list
pp.n_elem   = e;
pp.n_elec   = n_elec;
pp.n_node   = n;
pp.n_stim   = p;
pp.n_dims   = d-1;
pp.N2E      = N2E;
pp.boundary = bdy;
pp.normalize = mdl_normalize(fwd_model);
if p>0
  stim = fwd_model.stimulation;
  [pp.QQ, pp.VV, pp.n_meas] = calc_QQ_fast(N2E, stim, p);
  pp.v2meas   = get_v2meas(pp.n_elec, pp.n_stim, stim);
end
function v2meas = get_v2meas(n_elec,n_stim,stim)
    v2meas = sparse(n_elec*n_stim,0);
    for i=1:n_stim
        meas_pat= stim(i).meas_pattern;
        n_meas  = size(meas_pat,1);
        if n_elec ~= size(meas_pat,2)
           error('meas_pattern %d ~= n_elec',i)
        end
        v2meas((i-1)*n_elec + 1: i*n_elec,end+(1:n_meas)) = meas_pat.';
    end
    v2meas = v2meas'; % Conjugate transpose. For derivation
                      % see Chapter 5 of Adler&Holder 2021
% calculate element volume and surface area
function VOLUME = element_volume(NODE, ELEM, e, d)
   VOLUME=zeros(e,1);
   ones_d = ones(1,d);
   d1fac = prod( 1:d-1 );
   if d > size(NODE,1)
      for i=1:e
          this_elem = NODE(:,ELEM(:,i));
          VOLUME(i)= abs(det([ones_d;this_elem])) / d1fac;
      end
   elseif d == 3 % 3D nodes in 2D mesh
      for i=1:e
          this_elem = NODE(:,ELEM(:,i));
          d12= det([ones_d;this_elem([1,2],:)])^2;
          d13= det([ones_d;this_elem([1,3],:)])^2;
          d23= det([ones_d;this_elem([2,3],:)])^2;
          VOLUME(i)= sqrt(d12 + d13 + d23 ) / d1fac;
      end
   elseif d == 2 % 3D nodes in 1D mesh (ie resistor mesh)
      for i=1:e
          this_elem = NODE(:,ELEM(:,i));
          d12= det([ones_d;this_elem([1],:)])^2;
          d13= det([ones_d;this_elem([2],:)])^2;
          d23= det([ones_d;this_elem([3],:)])^2;
          VOLUME(i)= sqrt(d12 + d13 + d23 ) / d1fac;
      end
   else
      warning('mesh size not understood when calculating volumes')
      VOLUME = NaN;
   end
function [N2E,cem_electrodes] = calculate_N2E(fwd_model, bdy, n_elec, n);
   cem_electrodes= 0; % num electrodes part of Compl. Elec Model
   N2E = sparse(n_elec, n+n_elec);
   for i=1:n_elec
      eleci = fwd_model.electrode(i);
% The faces field is used only if
      if isfield(eleci,'faces')  && ~isempty(eleci.faces)
        if ~isempty(eleci.nodes)
           eidors_msg('Warning: electrode %d has both faces and nodes',i);
        end
        % This is a CEM electrode
        cem_electrodes = cem_electrodes+1;
        N2Ei= 1;
        N2Ei_nodes = n+cem_electrodes;
      elseif isfield(eleci,'nodes')
          elec_nodes = fwd_model.electrode(i).nodes;
         [N2Ei,N2Ei_nodes,cem_electrodes] =  ...
             N2Ei_from_nodes(fwd_model, ...
              bdy, elec_nodes, cem_electrodes,n);
      else
          eidors_msg('Warning: electrode %d has no nodes',i);
          break; %Not a real electrode so don't include
      end
      N2E(i, N2Ei_nodes) = N2Ei;
   end
   % Extra nodes are added if nodes for electronics components are added
   try
      extra_nodes = fwd_model.extra_nodes;
   catch
      extra_nodes = 0;
   end
   N2E = N2E(:, 1:(n+cem_electrodes+extra_nodes));
% If N2E can be made a logical (0-1) matrix, do it.
   if all(N2E(find(N2E(:)))==1)
      N2E = logical(N2E);
   end
function [N2Ei,N2Ei_nodes,cem_electrodes]= N2Ei_from_nodes(...
      fwd_model, bdy, elec_nodes, cem_electrodes,n);
  % Instrument nodes are added here like a CEM node but with no connections,
  % Use system_mat_instrument to add
  if ischar(elec_nodes) && strcmp(elec_nodes,'instrument')
     cem_electrodes = cem_electrodes+1;
     N2Ei= 1;
     N2Ei_nodes = n+cem_electrodes;
     return
  end
  if length(elec_nodes) ==1 % point electrode (maybe inside body)
     N2Ei = 1;
     N2Ei_nodes = elec_nodes;
  elseif length(elec_nodes) ==0
    error('EIDORS:fwd_model_parameters:electrode','zero length electrode specified');
  else
     bdy_idx= find_electrode_bdy( bdy, [], elec_nodes);
     if ~isempty(bdy_idx) % CEM electrode
        cem_electrodes = cem_electrodes+1;
        N2Ei= 1;
        N2Ei_nodes = n+cem_electrodes;
     else % a set of point electrodes
          % FIXME: make current defs between point electrodes and CEMs compatible
        [bdy_idx,srf_area]= find_electrode_bdy( bdy, ...
                       fwd_model.nodes, elec_nodes);
        s_srf_area =  sum(srf_area);
        if s_srf_area == 0;
           error('Surface area for elec#%d is zero. Is boundary correct?',i);
        end
        N2Ei = srf_area/s_srf_area;
        N2Ei_nodes= elec_nodes;
     end
  end
function [QQ, VV, n_meas] = calc_QQ_slow(N2E, stim, p)
   QQ = sparse(size(N2E,2),p);
   VV = sparse(size(N2E,2),p); N2E0 = N2E>0;
   n_meas= 0; % sum total number of measurements
   for i=1:p
       src= zeros(size(N2E,2),1);
       try;  src =       N2E' * stim(i).stim_pattern; end
       try;  src = src + stim(i).interior_sources;    end
       if all(size(src) == [1,1]) && src==0
          error('no stim_patterns or interior_sources provided for pattern #%d',i);
       end
       QQ(:,i) = src;
       n_meas = n_meas + size(stim(i).meas_pattern,1);
       vlt= zeros(size(N2E,2),1);
       try;  vlt =      N2E0' * stim(i).volt_pattern; end
       VV(:,i) = vlt;
   end
function [QQ, VV, n_meas] = calc_QQ_fast(N2E, stim, p)
   try
      ncols = arrayfun(@(x) size(x.stim_pattern,2), stim);
   catch
      error('EIDORS:fwd_model_parameters stim_pattern not specified');
   end
   if any(ncols>1);
      str = 'multiple columns in stim_pattern for patterns: ';
      error('EIDORS:fwd_model_parameters:stim_pattern', ...
            [str, sprintf('#%d ',find(ncols>1))]);
   end
   idx = 1:p; idx(ncols==0)= [];
   QQ = sparse(size(N2E,2),p);
   try
   QQ(:,idx) = N2E' * horzcat( stim(:).stim_pattern );
   end
   VV = sparse(size(N2E,2),p);
   % For voltages, we just need to know which N2E, not the size
   try
   ncols = arrayfun(@(x) size(x.volt_pattern,2), stim);
   end
   if any(ncols>1);
      str = 'multiple columns in volt_pattern for patterns: ';
      error('EIDORS:fwd_model_parameters:volt_pattern', ...
            [str, sprintf('#%d ',find(ncols>1))]);
   end
   idx = 1:p; idx(ncols==0)= [];
   try
   VV(:,idx) = (N2E>0)' * horzcat( stim(:).volt_pattern );
   end
   n_meas = size(vertcat(stim(:).meas_pattern),1);
function do_unit_test
   imdl = mk_common_model('a2c2',16); fmdl = imdl.fwd_model;
   pp = fwd_model_parameters(fmdl);
   [QQ1, VV1, n1m] = calc_QQ_slow(pp.N2E, fmdl.stimulation, pp.n_stim);
   [QQ2, VV2, n2m] = calc_QQ_fast(pp.N2E, fmdl.stimulation, pp.n_stim);
   unit_test_cmp('calc_QQ', norm(QQ1-QQ2,'fro') + norm(n1m-n2m), 0, 1e-15);
   unit_test_cmp('calc_VV1', norm(VV1,'fro'), 0, 1e-15);
   unit_test_cmp('calc_VV2', norm(VV2,'fro'), 0, 1e-15);
   for i=1:6;
      imdl = mk_common_model('a2C0',4); fmdl = imdl.fwd_model;
      switch i
         case 1; fmdl.stimulation(3).stim_pattern = fmdl.stimulation(3).stim_pattern*[1,2];
                 expected_err = 'EIDORS:fwd_model_parameters:stim_pattern';
         case 2; fmdl.stimulation(1).stim_pattern = [];
                 expected_err = ''; expected = zeros(45,4);
                 expected(42:45,2:4) = [0,0,1;-1,0,0;1,-1,0;0,1,-1]*10;
                 param = 'QQ';
         case 3; fmdl.electrode(1).nodes = [];
                 expected_err = 'EIDORS:fwd_model_parameters:electrode';
         case 4; fmdl.stimulation(1).volt_pattern = [zeros(3,1);6];
                 expected_err = ''; expected = zeros(45,4); expected(45,1) = 6;
                 param = 'VV';
         case 5; fmdl.stimulation(3).volt_pattern = [ones(4,2)];
                 expected_err = 'EIDORS:fwd_model_parameters:volt_pattern';
         case 6; fmdl.electrode(3).faces = [1,2;2,3;3,1];
                 fmdl.electrode(3).nodes = [];
                 expected_err = ''; expected = zeros(4,45);
                 expected(:,42:45) = eye(4);
                 param = 'N2E';
      end
      err= '';
      try;  pp = fwd_model_parameters(fmdl);
      catch e
         err= e.identifier;
      end
      if length(expected_err)>0;
         unit_test_cmp(['expected error:',num2str(i)], err, expected_err);
      else
         unit_test_cmp(['case:',num2str(i)], full(pp.(param)), expected);
      end
   end