Description of system_mat_fields
Home > eidors > solvers > forward > system_mat_fields.m
system_mat_fields
PURPOSE
SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
SYNOPSIS
function FC= system_mat_fields(fwd_model)
DESCRIPTION
 SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
 FC= system_mat_fields( fwd_model )
 input:
   fwd_model = forward model
 output:
   FC:        s_mat= C' * S * conduct * C = FC' * conduct * FC;
 system_mat_fields detects whether an electrode is a CEM by checking
  1) whether it has more than 1 node, and 2) if it's on the boundary
 If you want an internal CEM that's not on the boundary, then it
 has to be specified by using
    fmdl.system_mat_fields.CEM_boundary = [extra boundary ]
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG eidors progress and status messages
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_image MK_IMAGE: create eidors image object
num_elecs NUM_ELECS: number of electrodes attached to model
num_elems NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
num_nodes NUM_NODES: number of elemnts in a (fwd or inv model or image)
stim_meas_list STIM_MEAS_LIST: mk stimulation pattern from list of electrodes
sparse SPARSE Create sparse matrix (EIDORS overload).
find_boundary [srf, idx] = find_boundary(simp);
find_electrode_bdy FIND_ELECTRODE_BDY: find the boundary index area for electrode
fwd_model_parameters FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order(fwd_model, image)
system_mat_fields SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
eidors_cache EIDORS_CACHE Control eidors caching
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
vectorize_inverse vectorize_inverse: fast computation of 3x3 and 4x4 inverses
This function is called by:
aa_calc_system_mat AA_CALC_SYSTEM_MAT: SS= aa_calc_system_mat(fwd_model, img)
aa_system_mat_fields AA_SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
calc_model_reduction calc_model_reduction: calculate the fields for a reduced model
jacobian_adjoint JACOBIAN_ADJOINT: J= jacobian_adjoint(img)
jacobian_adjoint_2p5d_1st_order JACOBIAN_ADJOINT_2P5D: J= jacobian_adjoint_2p5d_1st_order(img)
system_mat_1st_order SYSTEM_MAT_1ST_ORDER: SS= system_mat_1st_order(fwd_model, img)
system_mat_2p5d_1st_order SYSTEM_MAT_2P5D_1ST_ORDER: 2.5D system matrix
system_mat_2p5d_fields SYSTEM_MAT_2P5D_FIELDS: fields (elem to nodes) fraction of system mat
system_mat_fields SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
update_system_mat_fields UPDATE_SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
SUBFUNCTIONS
function cache_obj = mk_cache_obj(fwd_model)
function FC= calc_system_mat_fields(fwd_model)
function [FFdata,FFiidx,FFjidx, CCdata,CCiidx,CCjidx] =
function [i_cem, sidx, cidx, blk]=compl_elec_mdl_i(
function FFdata = assemble_elements(d1,d0,p);
function do_unit_test
function do_unit_test_3d_test
function do_unit_test_2d_test
SOURCE CODE
function FC= system_mat_fields(fwd_model)
% SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
% FC= system_mat_fields(fwd_model)
% input:
%   fwd_model = forward model
% output:
%   FC:        s_mat= C' * S * conduct * C = FC' * conduct * FC;
%
% system_mat_fields detects whether an electrode is a CEM by checking
%  1) whether it has more than 1 node, and 2) if it's on the boundary
% If you want an internal CEM that's not on the boundary, then it
% has to be specified by using
%    fmdl.system_mat_fields.CEM_boundary = [extra boundary ]
% (C) 2008-2018 Andy Adler. License: GPL version 2 or version 3
% $Id: system_mat_fields.m 6481 2022-12-26 10:42:06Z aadler $
if ischar(fwd_model) && strcmp(fwd_model,'UNIT_TEST'); do_unit_test; return; end
copt.cache_obj = mk_cache_obj(fwd_model);
copt.fstr = 'system_mat_fields';
copt.log_level = 4;
FC= eidors_cache(@calc_system_mat_fields,{fwd_model},copt);
% only cache stuff which is really relevant here
function cache_obj = mk_cache_obj(fwd_model)
   cache_obj.elems       = fwd_model.elems;
   cache_obj.nodes       = fwd_model.nodes;
   try
   cache_obj.electrode   = fwd_model.electrode; % if we have it
   end
   cache_obj.type        = 'fwd_model';
   cache_obj.name        = ''; % it has to have one
function FC= calc_system_mat_fields(fwd_model)
   p= fwd_model_parameters( fwd_model, 'skip_VOLUME' );
   d0= p.n_dims+0;
   d1= p.n_dims+1;
   e= p.n_elem;
   n= p.n_node;
   if length(unique(fwd_model.elems(:)))~=n
       warning('EIDORS:unused_nodes','Number of nodes inconsistent with Elements. Consider using "remove_unused_nodes"');
   end
   FFjidx= floor([0:d0*e-1]'/d0)*d1*ones(1,d1) + ones(d0*e,1)*(1:d1);
   FFiidx= [1:d0*e]'*ones(1,d1);
   FFdata = assemble_elements(d1,d0,p);
if 0 % Not complete electrode model
   FF= sparse(FFiidx,FFjidx,FFdata);
   CC= sparse((1:d1*e),p.ELEM(:),ones(d1*e,1), d1*e, n);
else
   [F2data,F2iidx,F2jidx, C2data,C2iidx,C2jidx] = ...
             compl_elec_mdl(fwd_model,p);
   FF= sparse([FFiidx(:); F2iidx(:)],...
              [FFjidx(:); F2jidx(:)],...
              [FFdata(:); F2data(:)]);
   CC= sparse([(1:d1*e)';    C2iidx(:)], ...
      [double(p.ELEM(:));    C2jidx(:)], ...
              [ones(d1*e,1); C2data(:)]);
end
FC= FF*CC;
% Add parts for complete electrode model
function [FFdata,FFiidx,FFjidx, CCdata,CCiidx,CCjidx] = ...
             compl_elec_mdl(fmdl,pp)
   d0= pp.n_dims;
   FFdata= zeros(0,d0);
   FFiidx= zeros(0,d0);
   FFjidx= zeros(0,d0);
   CCdata= zeros(0,d0);
   CCiidx= zeros(0,d0);
   CCjidx= zeros(0,d0);
   sidx= d0*pp.n_elem;
   cidx= (d0+1)*pp.n_elem;
   i_cem = 0; % Index into electrodes that are CEM (but not pt)
   pp.cem_boundary = pp.boundary;
   if isfield(fmdl,'system_mat_fields')
      pp.cem_boundary = [pp.cem_boundary;
          fmdl.system_mat_fields.CEM_boundary];
      pp.cem_boundary = unique(pp.cem_boundary, ...
          'rows','stable');
          % TODO, how does this get duplicated
   end
   for i= 1:pp.n_elec
      eleci = fmdl.electrode(i);
      % contact impedance zc is in [Ohm.m] for 2D or [Ohm.m^2] for 3D
      zc=  eleci.z_contact;
      [i_cem, sidx, cidx, blk]= compl_elec_mdl_i( ...
         eleci, zc, i_cem, sidx, cidx, fmdl, pp);
      FFdata= [FFdata;blk.FFdata];
      FFiidx= [FFiidx;blk.FFiidx];
      FFjidx= [FFjidx;blk.FFjidx];
      CCdata= [CCdata;blk.CCdata];
      CCiidx= [CCiidx;blk.CCiidx];
      CCjidx= [CCjidx;blk.CCjidx];
   end
function [i_cem, sidx, cidx, blk]=compl_elec_mdl_i(...
       eleci, zc, i_cem, sidx, cidx, fmdl, pp);
   d0= pp.n_dims;
   FFd_block= sqrtm( ( ones(d0) + eye(d0) )/6/(d0-1) ); % 6 in 2D, 12 in 3D
   FFi_block= ones(d0,1)*(1:d0);
   blk.FFdata= zeros(0,d0);
   blk.FFiidx= zeros(0,d0);
   blk.FFjidx= zeros(0,d0);
   blk.CCdata= zeros(0,d0);
   blk.CCiidx= zeros(0,d0);
   blk.CCjidx= zeros(0,d0);
   if isfield(eleci,'faces')  && ~isempty(eleci.faces)
      if ~isempty(eleci.nodes)
         eidors_msg('Warning: electrode %d has both faces and nodes',i);
      end
      bdy_nds= eleci.faces;
      [~, bdy_area] = find_electrode_bdy( ...
          bdy_nds, fmdl.nodes,[]);
   else
      [bdy_idx, bdy_area] = find_electrode_bdy( ...
        pp.cem_boundary, fmdl.nodes, eleci.nodes);
          % bdy_area is in [m] for 2D or [m^2] for 3D
      % For pt elec model, bdy_idx = [], so this doesn't run
      if isempty(bdy_idx); return; end % no action for pt elecs
      bdy_nds= pp.cem_boundary(bdy_idx,:);
   end
   i_cem = i_cem + 1;
      % 3D: [m^2]/[Ohm.m^2] = [S]
      % 2D: [m]  /[Ohm.m]   = [S]
%    for j= 1:size(bdy_nds,1);
%       blk.FFdata= [blk.FFdata; FFd_block * sqrt(bdy_area(j)/zc)];
%       blk.FFiidx= [blk.FFiidx; FFi_block' + sidx];
%       blk.FFjidx= [blk.FFjidx; FFi_block  + cidx];
%
%       blk.CCiidx= [blk.CCiidx; FFi_block(1:2,:) + cidx];
%       blk.CCjidx= [blk.CCjidx; bdy_nds(j,:) ; (pp.n_node+i_cem)*ones(1,d0)];
%       blk.CCdata= [blk.CCdata; [1;-1]*ones(1,d0)];
%       sidx = sidx + d0;
%       cidx = cidx + d0;
%    end
   N = size(bdy_nds,1);
   blk.FFdata = kron(sqrt(bdy_area(:)/zc), FFd_block);
   blk.FFiidx = repmat(FFi_block',N,1) + kron(d0*(0:(N-1))',ones(d0)) + sidx;
   blk.FFjidx = repmat(FFi_block ,N,1) + kron(d0*(0:(N-1))',ones(d0)) + cidx;
   blk.CCiidx = repmat(FFi_block(1:2,:),N,1) + kron(d0*(0:(N-1))',ones(2,d0)) + cidx;
   blk.CCjidx = (pp.n_node+i_cem) * ones(2*N,d0);
   blk.CCjidx(1:2:end,:) = bdy_nds;
   blk.CCdata = ones(2*N, d0);
   blk.CCdata(2:2:end,:) = -1;
   sidx = sidx + N*d0;
   cidx = cidx + N*d0;
function  FFdata = assemble_elements(d1,d0,p);
   dfact = (d0-1)*d0;
   if 0 % OLD CODE
       FFdata= zeros(d0*p.n_elem,d1);
       for j=1:p.n_elem;
         a=  inv([ ones(d1,1), p.NODE( :, p.ELEM(:,j) )' ]);
         idx= d0*(j-1)+1 : d0*j;
         FFdata(idx,1:d1)= a(2:d1,:)/ sqrt(dfact*abs(det(a)));
       end %for j=1:ELEMs
   end
   M3 = ones(d1,d1,p.n_elem);
   M3(2:end,:,:)= reshape(p.NODE(:,p.ELEM),d0,d1,[]);
% To stabilize inverse, remove average
% This is a multiple of row1 = 1
% This affects row one only
   M3(2:end,:,:) = bsxfun(@minus, M3(2:end,:,:), ...
              mean(M3(2:end,:,:),2));
   [I,D] = vectorize_inverse(M3);
   Is = bsxfun(@times, I, sqrt(abs(D)/dfact));
   Is = permute(Is(:,2:d1,:),[2,3,1]);
   FFdata= reshape(Is,[],d1);
function do_unit_test
   do_unit_test_2d_test
   do_unit_test_3d_test
function do_unit_test_3d_test
   imdl= mk_common_model('n3r2',[16,2]);
   fmdl= imdl.fwd_model;
   FC = system_mat_fields( fmdl );
   SZ(2) = num_nodes(fmdl) + num_elecs(fmdl);
   SZ(1) = 3*(num_elems(fmdl) + num_elecs(fmdl)*2);
     % Two faces per electrode
   unit_test_cmp('sys_mat3d', size(FC), SZ);
   E14 = [...
   0.329216512695190  -0.329216512695190  0                   0;
   0.032424996343701  -0.032424996343701 -0.506252451622855   0.506252451622855;
  -0.098764953808557                   0  0.098764953808557                   0;
   0.329216512695190  -0.329216512695190  0                   0];
   unit_test_cmp('sys_mat3dx1', FC(1:4,[1,33,64,65]), E14,1e-14);
function do_unit_test_2d_test
   imdl=  mk_common_model('a2c2',16);
   FC = system_mat_fields( imdl.fwd_model);
   unit_test_cmp('sys_mat1', size(FC), [128,41]);
   unit_test_cmp('sys_mat2', FC(1:2,:), [[0,-1,1,0;-2,1,1,0], zeros(2,37)]/2, 1e-14);
   % THis is a 45 degree rotation of the previous
   imdl=  mk_common_model('a2c0',16);
   FC2= system_mat_fields( imdl.fwd_model);
   M = sqrt(.5)*[1,-1;1,1];
   unit_test_cmp('sys_mat3', M*FC2(1:2,:), [[0,-1,1,0;-2,1,1,0], zeros(2,37)]/2, 1e-14);
   % Check we can handle partial CEM/pt electrodes
   imdl = mk_common_model('b2s',4); fmdl = imdl.fwd_model;
   fmdl.electrode([2,4])= []; % remove to simplify
   fmdl.stimulation = stim_meas_list([1,2,1,2]);
   FF = system_mat_fields(fmdl);
   unit_test_cmp('sys_mat_b2s_1a', size(FF), [256,81]);
   vh = fwd_solve( mk_image(fmdl,1) );
   unit_test_cmp('sys_mat_b2s_1b', vh.meas, 2.182865407049302, 1e-12);
   fmdl.electrode(2).nodes = [4:6];
   FF = system_mat_fields(fmdl);
   unit_test_cmp('sys_mat_b2s_2a', size(FF), [260,82]);
   vh = fwd_solve( mk_image(fmdl,1) );
   unit_test_cmp('sys_mat_b2s_2b', vh.meas, 1.807627806615849, 1e-12);
   fmdl.electrode(1).nodes = [76:78];
   FF = system_mat_fields(fmdl);
   unit_test_cmp('sys_mat_b2s_3a', size(FF), [264,83]);
   vh = fwd_solve( mk_image(fmdl,1) );
   unit_test_cmp('sys_mat_b2s_3b', vh.meas, 1.432226638247073, 1e-12);
   imdl=  mk_common_model('a2C2',4);
   fmdl=rmfield(imdl.fwd_model,'stimulation');
   fmdl.nodes(1,:) = [];
   fmdl.gnd_node = 2;
   fmdl.elems(1:4,:) = [];
   fmdl.elems = fmdl.elems - 1;
   fmdl.boundary = find_boundary(fmdl);
   FC = system_mat_fields( fmdl);
   unit_test_cmp('sys_mat-bdyCEM-1', size(FC),[128,44]);
   unit_test_cmp('sys_mat-bdyCEM-2', FC(121:end,41:end), ...
             -13.967473716321374*kron(eye(4),[1;1]),1e-12)
% Add a CEM via a boundary
   fmdl.electrode(5) = struct('nodes',1:4,'z_contact',.01);
   FC = system_mat_fields( fmdl);
   unit_test_cmp('sys_mat-ctrCEM-1', size(FC),[136,45]);
   unit_test_cmp('sys_mat-ctrCEM-2', FC(121:128,41:44), ...
             -13.967473716321374*kron(eye(4),[1;1]),1e-12)
   unit_test_cmp('sys_mat-ctrCEM-2', FC(129:end,end), ...
             -4.204482076268572,1e-12)
% Add a CEM via a boundary
   Nelec = 4;
   imdl= mk_common_model('a2C2',Nelec);
   fmdl=rmfield(imdl.fwd_model,'stimulation');
   FC = system_mat_fields( fmdl );
   unit_test_cmp('sys_mat-b2cCEM-0', Nelec, num_elecs(fmdl));
   fmdl.electrode(3).nodes = []; % no longer a node elec
   fmdl.electrode(3).faces = [1,2;2,3;3,1];
   FC = system_mat_fields( fmdl);
%spy(FC)
%for i=129:148; disp([i,find(FC(i,:))]); end
%full(FC(129:end,1:3))
   unit_test_cmp('sys_mat-b2cCEM-1', size(FC), ...
       [num_elems(fmdl)*(size(fmdl.elems,2)-1) + 3*2 + 2*3, ...
        num_nodes(fmdl)+num_elecs(fmdl)]);
   imdl= mk_common_model('a2C2',Nelec);
   fmdl= rmfield(imdl.fwd_model,'stimulation');
   fmdl.electrode(5) = struct('nodes',1:3,'z_contact',.01);
   fmdl.system_mat_fields.CEM_boundary = [1,2;2,3;3,1];
   FC = system_mat_fields( fmdl );
   d1=num_elems(fmdl)*(size(fmdl.elems,2)-1) + ...
        4*2 + 2*3;
   d2= num_nodes(fmdl)+num_elecs(fmdl);
   unit_test_cmp('sys_mat-b2cCEM-1', size(FC),[d1,d2]);
   unit_test_cmp('sys_mat-b2cCEM-3', FC(129:136,42:45), ...
             -13.967473716321374*kron(eye(4),[1;1]),1e-12)
   unit_test_cmp('sys_mat-ctrCEM-4', FC([137:138,141:142],end), ...
             -3.535533905932737, 1e-12);
   unit_test_cmp('sys_mat-ctrCEM-5', FC([139:140],end), ...
             -4.204482076268572, 1e-12);