Description of gmsh_mk_2d_model
Home > eidors > meshing > gmsh > gmsh_mk_2d_model.m
gmsh_mk_2d_model
PURPOSE
GMSH_MK_2D_MODEL create a 2D mesh with GMSH
SYNOPSIS
function mdl = gmsh_mk_2d_model(varargin)
DESCRIPTION
GMSH_MK_2D_MODEL create a 2D mesh with GMSH
 mdl = gmsh_mk_2d_model(shape)
 SHAPE can be:
  - xy (Nx2)             : a counter- clockwise list of points in 2D
                           defining the outer contour
  - {xy, xy1, xy2, ...}  : allows specifying additional counter-clockwise
                           loops  xy1, xy2, etc, which represent holes in
                           the bigger contour xy contour
  - {..., maxsz}         : specifies the characteristic length at each
                           point (default: 0.1);
 For sufficently large MAXSZ, no new points are created on the boundary.
  See also NG_MK_2D_MODEL
CROSS-REFERENCE INFORMATION
This function calls:
eidors_obj EIDORS_OBJ: maintains EIDORS internals
show_fem SHOW_FEM: show the EIDORS3D finite element model
call_gmsh call_gmsh: call Gmsh to create a vol_file from a geo_file
gmsh_mk_2d_model GMSH_MK_2D_MODEL create a 2D mesh with GMSH
gmsh_read_mesh [srf,vtx,fc,bc,simp,edg,mat_ind,phys_names,entities] = gmsh_read_mesh(filename)
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
gmsh_mk_2d_model GMSH_MK_2D_MODEL create a 2D mesh with GMSH
SUBFUNCTIONS
function fname = write_geo_file(shape, cl, namestem)
function [shape, cl] = process_input(shape)
function do_unit_test
SOURCE CODE
function mdl = gmsh_mk_2d_model(varargin)
%GMSH_MK_2D_MODEL create a 2D mesh with GMSH
% mdl = gmsh_mk_2d_model(shape)
%
% SHAPE can be:
%  - xy (Nx2)             : a counter- clockwise list of points in 2D
%                           defining the outer contour
%  - {xy, xy1, xy2, ...}  : allows specifying additional counter-clockwise
%                           loops  xy1, xy2, etc, which represent holes in
%                           the bigger contour xy contour
%  - {..., maxsz}         : specifies the characteristic length at each
%                           point (default: 0.1);
%
% For sufficently large MAXSZ, no new points are created on the boundary.
%
%  See also NG_MK_2D_MODEL
%% (C) 2021 Bartlomiej Grychtol, License: GPL version 2 or version 3
% $Id: gmsh_mk_2d_model.m 6420 2022-11-29 15:08:09Z aadler $
if nargin==1 && ischar(varargin{1}) && strcmp(varargin{1},'UNIT_TEST'); do_unit_test; return; end
[shape, cl] = process_input(varargin{:});
namestem = tempname;
write_geo_file(shape, cl, namestem);
call_gmsh([namestem '.geo']);
[srf,vtx,fc,bc,simp,edg,mat_ind] = gmsh_read_mesh([namestem '.msh']);
mdl.type     = 'fwd_model';
mdl.name = 'gmsh_2d_model';
mdl.nodes    = vtx;
mdl.elems    = simp;
mdl= eidors_obj('fwd_model', mdl);
delete([namestem '.geo']);
delete([namestem '.msh']);
function fname = write_geo_file(shape, cl, namestem)
fname = [namestem '.geo'];
n_points = 0;
n_lines = 0;
loop_idx = [];
fid= fopen(fname,'w');
for i = 1:length(shape)
    n_sh_pts = size(shape{i},1);
    for p = 1:n_sh_pts
        fprintf(fid,'Point(%d) = {%f, %f, 0, %f};\n',...
            n_points + p, shape{i}(p,1), shape{i}(p,2), cl);
    end
    for p = 1:n_sh_pts-1
        fprintf(fid,'Line(%d) = {%d, %d};\n',...
            n_lines + p, n_points + p, n_points + p + 1);
    end
    fprintf(fid,'Line(%d) = {%d, %d};\n',...
        n_lines + n_sh_pts, n_points + n_sh_pts, n_points + 1);
    fprintf(fid,'Line Loop (%d) = {%d%s};\n',...
        n_lines + n_sh_pts + 1, n_lines + 1,...
        sprintf(', %d', n_lines + (2:n_sh_pts)));
    loop_idx = [loop_idx, n_lines + n_sh_pts + 1];
    n_points = n_points + n_sh_pts;
    n_lines = n_lines + n_sh_pts + 1;
end
str = '';
if numel(loop_idx) > 1
    str = sprintf(', %d', loop_idx(2:end));
end
fprintf(fid,'Plane Surface (%d) = {%d%s};\n',...
        n_lines + 1, loop_idx(1), str);
fclose(fid);
function [shape, cl] = process_input(shape)
cl = 0.1;
if ~iscell(shape)
   shape = {shape};
end
if numel(shape) > 1 && numel(shape{end}) == 1
    cl = shape{end};
    shape(end) = [];
end
function do_unit_test
  th=linspace(0,2*pi,9);
  th(end) = [];
  xy = [cos(th);sin(th)]';
  fmdl=gmsh_mk_2d_model(xy);
  subplot(331); show_fem(fmdl)
  title 'standard'
  unit_test_cmp('stop sign 01', max(fmdl.nodes), [1,1]);
  unit_test_cmp('stop sign 02', min(fmdl.nodes),-[1,1]);
  fmdl=gmsh_mk_2d_model({xy,0.5});
  subplot(332); show_fem(fmdl)
  title 'coarse'
  fmdl=gmsh_mk_2d_model({xy,xy*0.5,0.2});
  subplot(333); show_fem(fmdl)
  title 'hole'