Description of ng_mk_geometric_models
Home > eidors > meshing > netgen > ng_mk_geometric_models.m
ng_mk_geometric_models
PURPOSE
NG_MK_GEOMETRIC_MODELS: create geometric mesh models using Netgen. Body
SYNOPSIS
function [fmdl, mat_idx] = ng_mk_geometric_models(body_geometry, electrode_geometry)
DESCRIPTION
 NG_MK_GEOMETRIC_MODELS: create geometric mesh models using Netgen. Body
 and electrodes are defined as combinations of solid primitives. The 3-D
 surface intersection of the electrode and body volumes define the
 electrode surfaces.
[fmdl, mat_idx] = ng_mk_geometric_models(body_geometry, electrode_geometry)
 INPUT:
  body_geometry      - Structure whose fields describe body geometries as
                       combinations of unions, intersections and
                       complements of solid primitives. Cell array
                       should be used when describing several body
                       geometries.
  electrode_geometry - Structure whose fields describe electrode
                       geometries as combinations of unions, intersections
                       and complements of solid primitives. Cell array
                       should be used when describing several electrode
                       geometries.
 The following field names are available for geometry descriptions. Each
 field is followed by the available subfields whose default values if left
 unspecified are indicated between parentheses.
 complement_flag:    If true, the desired geometry description is the
                     complement of the geometry description. (false)
 body_of_revolution: A body of revolution is described with the following
                     subfields: axis_point_a ([0; 0; 0]), axis_point_b
                     ([0; 0; 1]), points (1 1; 1 2; 2 2; 2 1]),
                     segments ([1 2; 2 3; 3 4; 4 1]), complement_flag
                     (false).
 cone:               A cone is described with the following subfields:
                     bottom_center ([0; 0; 0]), bottom_radius (1),
                     top_center ([0; 0; 1]), top_radius (0.5),
                     complement_flag (false).
 cylinder:           A cylinder is described with the following subfields:
                     bottom_center ([0; 0; 0]), top_center ([0; 0; 1]),
                     radius (1), complement_flag (false).
 ellipsoid:          An ellipsoid is described with the following
                     subfields: center ([0; 0; 0]), axis_a ([1; 0; 0]),
                     axis_b ([0; 1; 0]), axis_c ([0; 0; 1]),
                     complement_flag (false).
 elliptic_cylinder:  An elliptic cylinder is described with the following
                     subfields: bottom_center ([0; 0; 0]),
                     top_center ([0; 0; 1]), axis_a ([1; 0; 0]),
                     axis_b ([0; 1; 0]), complement_flag (false).
 enter_body_flag:    This flag can be used only for electrode geometry
                     descriptions to indicate that the associated
                     electrode solid enters the body solids. It can only
                     be defined at the top level of each geometry
                     description. If this flag is true, it means that the
                     volume of the electrode intersecting with any body is
                     part of the electrode, otherwise it is part of a
                     body. (false)
 half_space          A half-space is described by the following subfields:
                     point ([0; 0; 0]), outward_normal_vector ([0; 0; 1]),
                     complement_flag (false).
 intersection:       This fields indicates to perform the intersection of
                     all subfields. Subfields: complement_flag (false).
 keep_material_flag: This flag can be used only for electrode geometry
                     descriptions to indicate that the associated
                     electrode material should be kept in the final mesh.
                     It can only be defined at the top level of each
                     geometry description. If true, it means that the
                     volume of the electrode is meshed. Volume elements
                     that are part of the mesh are indicated in mat_idx
                     output argument. (false)
 max_edge_length:    This parameter is used to adjust the maximum size of
                     the element composing the mesh. It can only be used
                     at the top level of each geometry description. (inf)
 name:               This parameter is used to name the geometry
                     description.
 ortho_brick:        An ortho-brick is described by the following
                     subfields: opposite_corner_a ([0; 0; 0]),
                     opposite_corner_b ([1; 1; 1]), complement_flag
                     (false).
 parallelepiped:     A parallelepiped is described by the following
                     subfields: vertex ([0; 0; 0]), vector_a ([1; 0; 0]),
                     vector_b ([0; 1; 0]), vector_c ([0; 0; 1]),
                     complement_flag (false).
 point:              This parameter describes a point. It can only be used
                     at the top level of an electrode geometry
                     description. It must be the only field in the
                     structure. ([])
 sphere:             A sphere is described with the following subfields:
                     center ([0; 0; 0]), radius (1), complement_flag
                     (false).
 union:              This will perform the union of all its subfields.
                     There is an implicit union operator at the top level
                     of the geometry structure. Subfields: complement_flag
                     (false)
 OUTPUT:
  fmdl               - EIDORS forward model object.
  mat_idx            - Vector indicating for each mesh element the indices
                       of materials corresponding as separately defined
                       by input argument body_geometry.
 USAGE EXAMPLES:
 % 3D cylinder with radius 1. One plane of 16 electrodes with radius 0.1
   body_geometry.cylinder = struct;
   n_elect = 16;
   theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
   for i = 1:n_elect
     electrode_geometry{i}.sphere.center = [cos(theta(i)) sin(theta(i)) 0.5];
     electrode_geometry{i}.sphere.radius = 0.1;
   end
   fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG eidors progress and status messages
eidors_obj EIDORS_OBJ: maintains EIDORS internals
show_fem SHOW_FEM: show the EIDORS3D finite element model
show_fem_enhanced SHOW_FEM_ENHANCED: show the EIDORS3D finite element model
call_netgen CALL_NETGEN: call netgen to create a vol_file from a geo_file
ng_mk_geometric_models NG_MK_GEOMETRIC_MODELS: create geometric mesh models using Netgen. Body
mk_tet_c2f MK_TET_C2F - calculate a coarse2fine mapping for two tet-based models.
eidors_cache EIDORS_CACHE Control eidors caching
eidors_debug EIDORS_DEBUG Global managment of debug flags
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
ng_mk_geometric_models NG_MK_GEOMETRIC_MODELS: create geometric mesh models using Netgen. Body
ng_mk_common_model NG_MK_COMMON_MODEL: utility to create common models
SUBFUNCTIONS
function [fmdl_mat_idx] = mk_geometric_models(body_geometry, electrode_geometry)
function radius = assign_radius(struct, n_structs, struct_name, field_name, default_value)
function point = assign_point(struct, n_structs, struct_name, field_name, default_value)
function point_list = assign_list_of_3D_points(struct, n_structs, struct_name, field_name, default_value)
function segment_list = assign_list_of_2D_points(struct, n_structs, struct_name, field_name, default_value)
function segment_list = assign_list_of_2D_or_3D_points(struct, n_structs, struct_name, field_name, default_value)
function flag = assign_flag(struct, n_structs, struct_name, field_name, default_value)
function [extra_code extra_param] = parse_geometry_point(geometry)
function [geo_code extra_code extra_param] = parse_geometry(geometry, field_operator_string, element_operator_string)
function [geo_code extra_code] = parse_geometry_body_of_extrusion(body_of_extrusion, operator_string)
function [geo_code extra_code] = parse_geometry_body_of_revolution(body_of_revolution, operator_string)
function geo_code = parse_geometry_cone(cone, operator_string)
function [geo_code,extra_code] = parse_geometry_cylinder(cylinder, operator_string)
function geo_code = parse_geometry_ellipsoid(ellipsoid, operator_string)
function geo_code = parse_geometry_elliptic_cylinder(elliptic_cylinder, operator_string)
function geo_code = parse_geometry_half_space(half_space, operator_string)
function geo_code = parse_geometry_ortho_brick(ortho_brick, operator_string)
function geo_code = parse_geometry_parallelepiped(parallelepiped, operator_string)
function geo_code = parse_geometry_sphere(sphere, operator_string)
function write_geo_file(geo_fn, body_solid_code, electrode_solid_code, body_extra_code, electrode_extra_code, body_extra_param, electrode_extra_param)
function mat = read_mat_from_file(fid, nrows, ncols)
function fmdl = read_vol_file(vol_fn, electrode_extra_param)
function fmdl = complete_fmdl(fmdl, electrode_extra_param)
function do_unit_test
function do_separate_internals_test
function do_combinations
function [fmdl, opts] = do_test_number(tn)
SOURCE CODE
function [fmdl, mat_idx] = ng_mk_geometric_models(body_geometry, electrode_geometry)
% NG_MK_GEOMETRIC_MODELS: create geometric mesh models using Netgen. Body
% and electrodes are defined as combinations of solid primitives. The 3-D
% surface intersection of the electrode and body volumes define the
% electrode surfaces.
%
%[fmdl, mat_idx] = ng_mk_geometric_models(body_geometry, electrode_geometry)
%
% INPUT:
%  body_geometry      - Structure whose fields describe body geometries as
%                       combinations of unions, intersections and
%                       complements of solid primitives. Cell array
%                       should be used when describing several body
%                       geometries.
%
%  electrode_geometry - Structure whose fields describe electrode
%                       geometries as combinations of unions, intersections
%                       and complements of solid primitives. Cell array
%                       should be used when describing several electrode
%                       geometries.
%
% The following field names are available for geometry descriptions. Each
% field is followed by the available subfields whose default values if left
% unspecified are indicated between parentheses.
%
% complement_flag:    If true, the desired geometry description is the
%                     complement of the geometry description. (false)
%
% body_of_revolution: A body of revolution is described with the following
%                     subfields: axis_point_a ([0; 0; 0]), axis_point_b
%                     ([0; 0; 1]), points (1 1; 1 2; 2 2; 2 1]),
%                     segments ([1 2; 2 3; 3 4; 4 1]), complement_flag
%                     (false).
%
% cone:               A cone is described with the following subfields:
%                     bottom_center ([0; 0; 0]), bottom_radius (1),
%                     top_center ([0; 0; 1]), top_radius (0.5),
%                     complement_flag (false).
%
% cylinder:           A cylinder is described with the following subfields:
%                     bottom_center ([0; 0; 0]), top_center ([0; 0; 1]),
%                     radius (1), complement_flag (false).
%
% ellipsoid:          An ellipsoid is described with the following
%                     subfields: center ([0; 0; 0]), axis_a ([1; 0; 0]),
%                     axis_b ([0; 1; 0]), axis_c ([0; 0; 1]),
%                     complement_flag (false).
%
% elliptic_cylinder:  An elliptic cylinder is described with the following
%                     subfields: bottom_center ([0; 0; 0]),
%                     top_center ([0; 0; 1]), axis_a ([1; 0; 0]),
%                     axis_b ([0; 1; 0]), complement_flag (false).
%
% enter_body_flag:    This flag can be used only for electrode geometry
%                     descriptions to indicate that the associated
%                     electrode solid enters the body solids. It can only
%                     be defined at the top level of each geometry
%                     description. If this flag is true, it means that the
%                     volume of the electrode intersecting with any body is
%                     part of the electrode, otherwise it is part of a
%                     body. (false)
%
% half_space          A half-space is described by the following subfields:
%                     point ([0; 0; 0]), outward_normal_vector ([0; 0; 1]),
%                     complement_flag (false).
%
% intersection:       This fields indicates to perform the intersection of
%                     all subfields. Subfields: complement_flag (false).
%
% keep_material_flag: This flag can be used only for electrode geometry
%                     descriptions to indicate that the associated
%                     electrode material should be kept in the final mesh.
%                     It can only be defined at the top level of each
%                     geometry description. If true, it means that the
%                     volume of the electrode is meshed. Volume elements
%                     that are part of the mesh are indicated in mat_idx
%                     output argument. (false)
%
% max_edge_length:    This parameter is used to adjust the maximum size of
%                     the element composing the mesh. It can only be used
%                     at the top level of each geometry description. (inf)
%
% name:               This parameter is used to name the geometry
%                     description.
%
% ortho_brick:        An ortho-brick is described by the following
%                     subfields: opposite_corner_a ([0; 0; 0]),
%                     opposite_corner_b ([1; 1; 1]), complement_flag
%                     (false).
%
% parallelepiped:     A parallelepiped is described by the following
%                     subfields: vertex ([0; 0; 0]), vector_a ([1; 0; 0]),
%                     vector_b ([0; 1; 0]), vector_c ([0; 0; 1]),
%                     complement_flag (false).
%
% point:              This parameter describes a point. It can only be used
%                     at the top level of an electrode geometry
%                     description. It must be the only field in the
%                     structure. ([])
%
% sphere:             A sphere is described with the following subfields:
%                     center ([0; 0; 0]), radius (1), complement_flag
%                     (false).
%
% union:              This will perform the union of all its subfields.
%                     There is an implicit union operator at the top level
%                     of the geometry structure. Subfields: complement_flag
%                     (false)
%
% OUTPUT:
%  fmdl               - EIDORS forward model object.
%
%  mat_idx            - Vector indicating for each mesh element the indices
%                       of materials corresponding as separately defined
%                       by input argument body_geometry.
%
% USAGE EXAMPLES:
% % 3D cylinder with radius 1. One plane of 16 electrodes with radius 0.1
%   body_geometry.cylinder = struct;
%   n_elect = 16;
%   theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
%   for i = 1:n_elect
%     electrode_geometry{i}.sphere.center = [cos(theta(i)) sin(theta(i)) 0.5];
%     electrode_geometry{i}.sphere.radius = 0.1;
%   end
%   fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
% (C) Herve Gagnon, 2015. Licenced under GPL v2 or v3
% $Id: ng_mk_geometric_models.m 6492 2022-12-28 17:19:21Z aadler $
% Check if function is called in UNIT_TEST mode.
if (ischar(body_geometry) && strcmp(body_geometry, 'UNIT_TEST'))
    do_unit_test;
    return;
end
% Validate function parameters.
if (isempty(body_geometry) || ~isstruct(body_geometry) && ~iscell(body_geometry))
   error('Parameter body_geometry must be a structure or a cell.');
end
% Check if parameter electrode_geometry is specified.
if (nargin < 2 || isempty(electrode_geometry))
    electrode_geometry = {};
end
if (~isstruct(electrode_geometry) && ~iscell(electrode_geometry))
   error('Parameter electrode_geometry must be a structure or a cell.');
end
% If parameters are not of cell type, convert them to cell.
if (~iscell(body_geometry))
    body_geometry = {body_geometry};
end
if (~iscell(electrode_geometry))
    electrode_geometry = {electrode_geometry};
end
% Check if result is already in cache. Otherwise, compute and store in cache.
copt.cache_obj = {body_geometry, electrode_geometry};
copt.fstr = 'ng_mk_geometric_models';
args = {body_geometry, electrode_geometry};
copt.cache_on_ng_opt = true;
fmdl_mat_idx = eidors_cache(@mk_geometric_models, args, copt);
% Reformat output arguments.
fmdl    = fmdl_mat_idx{1};
mat_idx = fmdl_mat_idx{2};
function [fmdl_mat_idx] = mk_geometric_models(body_geometry, electrode_geometry)
    % Find number of subdomains
    n_body      = numel(body_geometry);
    n_electrode = numel(electrode_geometry);
    % Allocate cell memory.
    body_solid_code       = cell(size(body_geometry));
    body_extra_code       = cell(size(body_geometry));
    body_extra_param      = cell(size(body_geometry));
    electrode_solid_code  = cell(size(electrode_geometry));
    electrode_extra_code  = cell(size(electrode_geometry));
    electrode_extra_param = cell(size(electrode_geometry));
    % Parse geometry for each body subdomain.
    for i = 1:n_body
        if (isfield(body_geometry{i}, 'point'))
            error('Field name "point" is not allowed for body geometry.');
        end
        if (isfield(body_geometry{i}, 'enter_body_flag'))
            error('Field name "enter_body_flag" is not allowed for body geometry.');
        end
        if (isfield(body_geometry{i}, 'keep_material_flag'))
            error('Field name "keep_material_flag" is not allowed for body geometry.');
        end
        [body_solid_code{i} body_extra_code{i} body_extra_param{i}] = parse_geometry(body_geometry{i});
    end
    % Parse geometry for each body subdomain.
    for i = 1:n_electrode
        [electrode_extra_code{i} electrode_extra_param{i}] = parse_geometry_point(electrode_geometry{i});
        if (isempty(electrode_extra_param{i}.point))
            [electrode_solid_code{i} electrode_extra_code{i} electrode_extra_param{i}] = parse_geometry(electrode_geometry{i});
        end
    end
    % Define temporary unique filenames.
    fn_prefix = tempname;
    geo_fn    = [fn_prefix, '.geo'];
    vol_fn    = [fn_prefix, '.vol'];
     % Add body names if unspecified.
    for i = 1:numel(body_solid_code)
        if (isempty(body_extra_param{i}.name))
            body_extra_param{i}.name = sprintf('body%04d', i);
        end
    end
    % Add electrode names if unspecified.
    for i = 1:numel(electrode_solid_code)
        if (isempty(electrode_extra_param{i}.name))
            electrode_extra_param{i}.name = sprintf('electrode%04d', i);
        end
    end
    % Write geo file for netgen.
    write_geo_file(geo_fn, body_solid_code, electrode_solid_code, body_extra_code, electrode_extra_code, body_extra_param, electrode_extra_param);
    % Call netgen.
    call_netgen(geo_fn, vol_fn);
    % Read vol file generated by netgen.
    fmdl_mat_idx{1} = read_vol_file(vol_fn, electrode_extra_param);
    % Delete temporary files.
    if ~eidors_debug('query','ng_mk_geometric_models:keep_temp_files')
       delete(geo_fn);
       delete(vol_fn);
    end
    % Complete fmdl object.
    fmdl_mat_idx{1} = complete_fmdl(fmdl_mat_idx{1}, electrode_extra_param);
    % Assign mat_idx value from fmdl.
    fmdl_mat_idx{2} = fmdl_mat_idx{1}.mat_idx;
function radius = assign_radius(struct, n_structs, struct_name, field_name, default_value)
    radius = default_value;
    for i = 1:n_structs
        value = struct(i).(field_name);
        if (~isempty(value))
            if (isscalar(value) && isnumeric(value) && isreal(value) && value > 0)
                radius(i) = value;
            else
                error('%s(%d).%s value is not valid.', struct_name, i, field_name);
            end
        end
    end
function point = assign_point(struct, n_structs, struct_name, field_name, default_value)
    point = default_value;
    for i = 1:n_structs
        value =  struct(i).(field_name);
        if (~isempty(value))
            if (numel(value) == 3 && isnumeric(value) && isreal(value))
                point(:, i) = value;
            else
                error('%s(%d).%s value is not valid.', struct_name, i, field_name);
            end
        end
    end
function point_list = assign_list_of_3D_points(struct, n_structs, struct_name, field_name, default_value)
    point_list = cell(n_structs, 1);
    for i = 1:n_structs
        point_list{i} = default_value;
        value = struct(i).(field_name);
        if (~isempty(value))
            if (size(value, 2) == 3 && isnumeric(value) && isreal(value))
                point_list{i} = value;
            else
                error('%s(%d).%s value is not valid.', struct_name, i, field_name);
            end
        end
    end
function segment_list = assign_list_of_2D_points(struct, n_structs, struct_name, field_name, default_value)
    segment_list = cell(n_structs, 1);
    for i = 1:n_structs
        segment_list{i} = default_value;
        value = struct(i).(field_name);
        if (~isempty(value))
            if (size(value, 2) == 2 && isnumeric(value) && isreal(value))
                segment_list{i} = value;
            else
                error('%s(%d).%s value is not valid.', struct_name, i, field_name);
            end
        end
    end
 function segment_list = assign_list_of_2D_or_3D_points(struct, n_structs, struct_name, field_name, default_value)
    segment_list = cell(n_structs, 1);
    for i = 1:n_structs
        segment_list{i} = default_value;
        value = struct(i).(field_name);
        if (~isempty(value))
            if ((size(value, 2) == 2 || size(value, 2) == 3) && isnumeric(value) && isreal(value))
                segment_list{i} = value;
            else
                error('%s(%d).%s value is not valid.', struct_name, i, field_name);
            end
        end
    end
function flag = assign_flag(struct, n_structs, struct_name, field_name, default_value)
    flag = default_value;
    for i = 1:n_structs
        value = struct(i).(field_name);
        if (~isempty(value))
            if (isscalar(value) && (islogical(value) || (isnumeric(value) && ...
                                     isreal(value) && (value == 0 || value == 1))))
                flag(i) = value;
            else
value
                error('%s(%d).%s value is not valid.', struct_name, i, field_name);
            end
        end
    end
function [extra_code extra_param] = parse_geometry_point(geometry)
    % Initialize extra param values to default values.
    extra_code                     = '';
    extra_param.point              = [];
    extra_param.max_edge_length    = inf;
    extra_param.enter_body_flag    = false;
    extra_param.keep_material_flag = false;
    extra_param.name               = '';
    % Check if geometry is a point, return otherwise.
    if (isfield(geometry, 'point'))
        % Check if a single point is defined.
        if (numel(geometry) ~= 1)
            error('Field name "point" must define only a single point.');
        end
        % Get structure field names.
        field_names = fieldnames(geometry);
        n_fields = numel(field_names);
        % Check if it is the only field names.
        if (n_fields ~= 1)
            if (isfield(geometry, 'name'))
                extra_param.name = geometry.name;
            else
                error('Field name "point" must be used as a single field.');
            end
        end
        % Check point is 3D.
        if (numel(geometry.point) ~= 3)
            error('geometry.point value is not valid.');
        end
        % Set returning values.
        extra_param.point = geometry.point(:);
        extra_code = sprintf('point(%g, %g, %g);\n', extra_param.point);
    end
function [geo_code extra_code extra_param] = parse_geometry(geometry, field_operator_string, element_operator_string)
    % Extra code is initialized empty;
    extra_code = '';
    % Initialize extra param values to default values.
    extra_param.max_edge_length     = inf;
    extra_param.enter_body_flag     = false;
    extra_param.keep_material_flag  = false;
    extra_param.name                = '';
    % If called from top_level, operators default to or.
    if (nargin == 1)
        top_level_flag = 1;
        field_operator_string = ' or ';
        element_operator_string = ' or ';
    else
        top_level_flag = 0;
    end
    eidors_msg('@@@ called with (field: "%s", element: "%s").', field_operator_string, element_operator_string, 4);
    % Validate that geometry is a non-empty structure.
    if (~isstruct(geometry) || isempty(geometry))
        error('Parameter geometry must be a valid structure.');
    else
        % Get number of geometries.
        n_geometries = numel(geometry);
        % Get structure field names.
        field_names = fieldnames(geometry);
        n_fields = numel(field_names);
        % Recursively parse all geometry fields.
        geo_code = '(';
        for i = 1:n_geometries
            % complement_flag field has to be processed first.
            if (isfield(geometry(i), 'complement_flag') && ~isempty(geometry(i).complement_flag) && geometry(i).complement_flag)
                 geo_code = [geo_code '(not('];
            else
                 geo_code = [geo_code '('];
            end
            % Process name field.
            if (isfield(geometry(i), 'name'))
                if (~top_level_flag)
                    error('Field "name" can only be specified at the top level of the geometry description');
                end
                extra_param.name = geometry(i).name;
                if (isempty(extra_param.name) || ~ischar(extra_param.name))
                    error('name value is not valid.');
                end
            end
           % Process max_edge_length field.
            if (isfield(geometry(i), 'max_edge_length'))
                if (~top_level_flag)
                    error('Field "max_edge_length" can only be specified at the top level of the geometry description');
                end
                extra_param.max_edge_length = geometry(i).max_edge_length;
                if (isempty(extra_param.max_edge_length) || ~isscalar(extra_param.max_edge_length) || ~isnumeric(extra_param.max_edge_length) || ~isreal(extra_param.max_edge_length) || extra_param.max_edge_length <= 0)
                    error('max_edge_length value is not valid.');
                end
            end
            % Process enter_body_flag field.
            if (isfield(geometry(i), 'enter_body_flag'))
                if (~top_level_flag)
                    error('Field "enter_body_flag" can only be specified at the top level of the geometry description');
                end
                extra_param.enter_body_flag = geometry(i).enter_body_flag;
                if (isempty(extra_param.enter_body_flag) || ~isscalar(extra_param.enter_body_flag) || (~islogical(extra_param.enter_body_flag) && ...
                        (~isnumeric(extra_param.enter_body_flag) || ~isreal(extra_param.enter_body_flag) || (extra_param.enter_body_flag ~= 0 && extra_param.enter_body_flag ~= 1))))
                    error('Field "enter_body_flag value" is not valid.');
                end
            end
            % Process keep_material_flag field.
            if (isfield(geometry(i), 'keep_material_flag'))
                if (~top_level_flag)
                    error('Field "keep_material_flag" can only be specified at the top level of the geometry description');
                end
                extra_param.keep_material_flag = geometry(i).keep_material_flag;
                if (isempty(extra_param.keep_material_flag) || ~isscalar(extra_param.keep_material_flag) || (~islogical(extra_param.keep_material_flag) && ...
                        (~isnumeric(extra_param.keep_material_flag) || ~isreal(extra_param.keep_material_flag) || (extra_param.keep_material_flag ~= 0 && extra_param.keep_material_flag ~= 1))))
                    error('Field "keep_material_flag" value is not valid.');
                end
            end
            first_internal_term = 1;
            for j = 1:n_fields
                if (~isempty(geometry(i).(field_names{j})) && ~strcmp(field_names{j}, 'complement_flag') && ~strcmp(field_names{j}, 'name') && ~strcmp(field_names{j}, 'max_edge_length') && ~strcmp(field_names{j}, 'keep_material_flag') && ~strcmp(field_names{j}, 'enter_body_flag'))
                    if (first_internal_term)
                        first_internal_term = 0;
                    else
                        geo_code = [geo_code field_operator_string];
                    end
                    switch (field_names{j})
                        case 'body_of_extrusion'
                            [geo_code_temp extra_code_temp] = ...
                                        parse_geometry_body_of_extrusion(geometry(i).(field_names{j}), field_operator_string);
                            geo_code   = [geo_code geo_code_temp];
                            extra_code = [extra_code extra_code_temp];
                        case 'body_of_revolution'
                            [geo_code_temp extra_code_temp] = ...
                                        parse_geometry_body_of_revolution(geometry(i).(field_names{j}), field_operator_string);
                            geo_code   = [geo_code geo_code_temp];
                            extra_code = [extra_code extra_code_temp];
                        case 'cone'
                            geo_code = [geo_code ...
                                        parse_geometry_cone(geometry(i).(field_names{j}), field_operator_string)];
                        case 'cylinder'
                            [geo_code_temp, extra_code_temp] = ...
                                        parse_geometry_cylinder(geometry(i).(field_names{j}), field_operator_string);
                            geo_code   = [geo_code geo_code_temp];
                            extra_code = [extra_code extra_code_temp];
                        case 'ellipsoid'
                            geo_code = [geo_code ...
                                        parse_geometry_ellipsoid(geometry(i).(field_names{j}), field_operator_string)];
                        case 'elliptic_cylinder'
                            geo_code = [geo_code ...
                                        parse_geometry_elliptic_cylinder(geometry(i).(field_names{j}), field_operator_string)];
                        case 'half_space'
                            geo_code = [geo_code ...
                                        parse_geometry_half_space(geometry(i).(field_names{j}), field_operator_string)];
                        case 'ortho_brick'
                            geo_code = [geo_code ...
                                        parse_geometry_ortho_brick(geometry(i).(field_names{j}), field_operator_string)];
                        case 'parallelepiped'
                            geo_code = [geo_code ...
                                        parse_geometry_parallelepiped(geometry(i).(field_names{j}), field_operator_string)];
                        case 'sphere'
                            geo_code = [geo_code ...
                                        parse_geometry_sphere(geometry(i).(field_names{j}), field_operator_string)];
                        case 'intersection'
                            [geo_code_temp extra_code_temp] = ...
                                        parse_geometry(geometry(i).(field_names{j}), ' and ', field_operator_string);
                            geo_code   = [geo_code geo_code_temp];
                            extra_code = [extra_code extra_code_temp];
                        case 'union'
                            [geo_code_temp extra_code_temp] = ...
                                        parse_geometry(geometry(i).(field_names{j}), ' or ', field_operator_string);
                            geo_code   = [geo_code geo_code_temp];
                            extra_code = [extra_code extra_code_temp];
                        otherwise
                            error(['Field name "%s" is not valid for a geometry.\nAvailable field names for a geometry are: '...
                                   'complement_flag, intersection, union, body_of_extrusion, body_of_revolution, cone, cylinder, ellipsoid, elliptic_cylinder, half_space, ortho_brick, parallelepiped, point, sphere, keep_material_flag, enter_body_flag, name, and max_edge_length.'], field_names{j});
                    end
                end
            end
            if (isfield(geometry(i), 'complement_flag') && ~isempty(geometry(i).complement_flag) && geometry(i).complement_flag)
                geo_code = [geo_code '))'];
            else
                geo_code = [geo_code ')'];
            end
            if (i < n_geometries)
                geo_code = [geo_code element_operator_string];
            end
        end
        geo_code = [geo_code ')'];
    end
    eidors_msg('@@@ returned with (field: "%s", element: "%s").', field_operator_string, element_operator_string, 4);
function [geo_code extra_code] = parse_geometry_body_of_extrusion(body_of_extrusion, operator_string)
    eidors_msg('@@@ called with "%s" starting.', operator_string, 4);
    if (~isstruct(body_of_extrusion) || isempty(body_of_extrusion))
        error('Parameter body_of_extrusion must be a valid structure.');
    else
        % Get number of body_of_extrusion.
        n_body_of_extrusions = numel(body_of_extrusion);
        % Get structure field names.
        field_names = fieldnames(body_of_extrusion);
        n_fields = numel(field_names);
        % Assign default values.
        vector_d            = [0; 1; 0]*ones(1, n_body_of_extrusions);
        profile_points{1}   = [1 1; 1 2; 2 2; 2 1];
        profile_segments{1} = [1 2; 2 3; 3 4; 4 1];
        path_points{1}      = [0 0 0; 0 0 1; 0 0 2; 0 0 3];
        path_segments{1}    = [1 2; 2 3; 3 4];
        complement_flag     = false(1, n_body_of_extrusions);
        % Parse all structure fields.
        for i = 1:n_fields
            switch (field_names{i})
                case 'vector_d'
                    vector_d = assign_point(body_of_extrusion, n_body_of_extrusions, 'body_of_extrusion', field_names{i}, vector_d);
                case 'profile_points'
                    profile_points = assign_list_of_2D_points(body_of_extrusion, n_body_of_extrusions, 'body_of_extrusion', field_names{i}, profile_points{1});
                case 'profile_segments'
                    profile_segments = assign_list_of_2D_or_3D_points(body_of_extrusion, n_body_of_extrusions, 'body_of_extrusion', field_names{i}, profile_segments{1});
                case 'path_points'
                    path_points = assign_list_of_3D_points(body_of_extrusion, n_body_of_extrusions, 'body_of_extrusion', field_names{i}, path_points{1});
                case 'path_segments'
                    path_segments = assign_list_of_2D_or_3D_points(body_of_extrusion, n_body_of_extrusions, 'body_of_extrusion', field_names{i}, path_segments{1});
                case 'complement_flag'
                    complement_flag = assign_flag(body_of_extrusion, n_body_of_extrusions, 'body_of_extrusion', field_names{i}, complement_flag);
                otherwise
                    error(['Field name "%s" is not allowed for a body_of_extrusion!\nAllowed field names for a body_of_extrusion are: ' ...
                           'path_points, path_segments, profile_points, profile_segments, vector_d, and complement_flag.'], field_names{i});
            end
        end
        % Start geo code with an opening parenthesis.
        geo_code = '(';
        extra_code = '';
        % Add geo code for each body_of_extrusion.
        for i = 1:n_body_of_extrusions
            for j = 1:size(path_segments{i}, 1)
                if (dot(vector_d(:,i), path_points{i}(path_segments{i}(j, 1), :) - path_points{i}(path_segments{i}(j, end), :)) ~= 0)
                    error('vector_d and path must be perpendicular for a body of extrusion.');
                end
            end
            n_points = size(profile_points{i}, 1);
            n_segments = size(profile_segments{i}, 1);
            if (size(profile_segments{i}, 2) == 2)
                extra_code = [extra_code sprintf('curve2d Extrusion2DProfileCurve%d = (%g ; ', i, n_points) ...
                                         sprintf('%g, %g ; ', profile_points{i}') ...
                                         sprintf(' %g ', n_segments) ...
                                         sprintf('; 2, %g, %g ', profile_segments{i}') ...
                                         sprintf(');\n\n')];
            else
                extra_code = [extra_code sprintf('curve2d Extrusion2DProfileCurve%d = (%g ; ', i, n_points) ...
                                         sprintf('%g, %g ; ', profile_points{i}') ...
                                         sprintf(' %g ', n_segments) ...
                                         sprintf('; 3, %g, %g, %g ', profile_segments{i}') ...
                                         sprintf(');\n\n')];
            end
            n_points = size(path_points{i}, 1);
            n_segments = size(path_segments{i}, 1);
            if (size(path_segments{i}, 2) == 2)
                extra_code = [extra_code sprintf('curve3d Extrusion3DPathCurve%d = (%g ; ', i, n_points) ...
                                         sprintf('%g, %g, %g ; ', path_points{i}') ...
                                         sprintf(' %g ', n_segments) ...
                                         sprintf('; 2, %g, %g ', path_segments{i}') ...
                                         sprintf(');\n\n')];
            else
                 extra_code = [extra_code sprintf('curve3d Extrusion3DPathCurve%d = (%g ; ', i, n_points) ...
                                         sprintf('%g, %g, %g ; ', path_points{i}') ...
                                         sprintf(' %g ', n_segments) ...
                                         sprintf('; 3, %g, %g, %g ', path_segments{i}') ...
                                         sprintf(');\n\n')];
            end
            if (complement_flag(i))
                geo_code = [geo_code 'not '];
            end
            % Check if path is closed.
            if (path_segments{i}(end) == path_segments{i}(1))
                geo_code = [geo_code sprintf('extrusion(Extrusion3DPathCurve%d ; Extrusion2DProfileCurve%d ; %g, %g, %g)', i, i, vector_d(:,i))];
            else
                %error('Unclosed path are not yet supported for body of extrusion!');
                %for j = 1: [1 1; 1 2; 2 2; 2 1];
                %polyhedron1 = 'polyhedron(-1, 1, 0; -1, 2, 0; -2, 2, 0; -2, 1, 0; -1.5, 1.5, 0; -1.5, 1.5, 1 ;; 2, 1, 5; 3, 2, 5; 4, 3, 5; 1, 4, 5; 1, 2, 6; 2, 3, 6; 3, 4, 6; 4, 1, 6)';
                %polyhedron2 = 'polyhedron(-1, 1, 3; -1, 2, 3; -2, 2, 3; -2, 1, 3; -1.5, 1.5, 3; -1.5, 1.5, 2 ;; 1, 2, 5; 2, 3, 5; 3, 4, 5; 4, 1, 5; 2, 1, 6; 3, 2, 6; 4, 3, 6; 1, 4, 6)';
                %polyhedron1 = 'plane(0, 0, 3; 0, 0, 1)';
                %polyhedron2 = 'plane(0, 0, 0; 0, 0, -1)';
                first_point  = path_points{i}(path_segments{i}(1, 1), :);
                first_vector = first_point - path_points{i}(path_segments{i}(1, end), :);
                last_point   = path_points{i}(path_segments{i}(end, end), :);
                last_vector  = last_point - path_points{i}(path_segments{i}(end, 1), :);
                geo_code = [geo_code sprintf('(extrusion(Extrusion3DPathCurve%d ; Extrusion2DProfileCurve%d ; %g, %g, %g) and plane(%g, %g, %g; %g, %g, %g) and plane(%g, %g, %g; %g, %g, %g))', ...
                            i, i, vector_d(:,i), first_point, first_vector, last_point, last_vector)];
                %geo_code = [geo_code sprintf('(%s or %s)', polyhedron1, polyhedron2)];
            end
            if (i < n_body_of_extrusions)
                geo_code = [geo_code operator_string];
            else
                geo_code = [geo_code ')'];
            end
        end
    end
    eidors_msg('@@@ called with "%s" returning.', operator_string, 4);
function [geo_code extra_code] = parse_geometry_body_of_revolution(body_of_revolution, operator_string)
    eidors_msg('@@@ called with "%s" starting.', operator_string, 4);
    if (~isstruct(body_of_revolution) || isempty(body_of_revolution))
        error('Parameter body_of_revolution must be a valid structure.');
    else
        % Get number of body_of_revolution.
        n_body_of_revolutions = numel(body_of_revolution);
        % Get structure field names.
        field_names = fieldnames(body_of_revolution);
        n_fields = numel(field_names);
        % Assign default values.
        axis_point_a   = [0;0;0]*ones(1, n_body_of_revolutions);
        axis_point_b   = [0;0;1]*ones(1, n_body_of_revolutions);
        points{1}      = [1 1; 1 2; 2 2; 2 1];
        segments{1}    = [1 2; 2 3; 3 4; 4 1];
        complement_flag = false(1, n_body_of_revolutions);
        % Parse all structure fields.
        for i = 1:n_fields
            switch (field_names{i})
                case 'axis_point_a'
                    axis_point_a = assign_point(body_of_revolution, n_body_of_revolutions, 'body_of_revolution', field_names{i}, axis_point_a);
                case 'axis_point_b'
                    axis_point_b = assign_point(body_of_revolution, n_body_of_revolutions, 'body_of_revolution', field_names{i}, axis_point_b);
                case 'points'
                    points = assign_list_of_2D_points(body_of_revolution, n_body_of_revolutions, 'body_of_revolution', field_names{i}, points{1});
                case 'segments'
                    segments = assign_list_of_2D_or_3D_points(body_of_revolution, n_body_of_revolutions, 'body_of_revolution', field_names{i}, segments{1});
                case 'complement_flag'
                    complement_flag = assign_flag(body_of_revolution, n_body_of_revolutions, 'body_of_revolution', field_names{i}, complement_flag);
                otherwise
                    error(['Field name ''%s'' is not valid for a body_of_revolution.\Available field names for a body_of_revolution are: ' ...
                           'axis_point_a, axis_point_b, points, segments, and complement_flag.'], field_names{i});
            end
        end
        % Start geo code with an opening parenthesis.
        geo_code = '(';
        extra_code = '';
        % Add geo code for each body_of_revolution.
        for i = 1:n_body_of_revolutions
            n_points = size(points{i}, 1);
            n_segments = size(segments{i}, 1);
            if (size(segments{i}, 2) == 2)
                extra_code = [extra_code sprintf('curve2d Revolution2DCurve%d = (%g ; ', i, n_points) ...
                                               sprintf('%g, %g ; ', points{i}') ...
                                               sprintf(' %g ', n_segments) ...
                                               sprintf('; 2, %g, %g ', segments{i}') ...
                                               sprintf(');\n\n')];
            else
                extra_code = [extra_code sprintf('curve2d Revolution2DCurve%d = (%g ; ', i, n_points) ...
                                               sprintf('%g, %g ; ', points{i}') ...
                                               sprintf(' %g ', n_segments) ...
                                               sprintf('; 3, %g, %g, %g ', segments{i}') ...
                                               sprintf(');\n\n')];
            end
            if (complement_flag(i))
                geo_code = [geo_code 'not '];
            end
            geo_code = [geo_code sprintf('revolution(%g, %g, %g ; %g, %g, %g ; Revolution2DCurve%d)', ...
                        axis_point_a(:, i), axis_point_b(:, i), i)];
            if (i < n_body_of_revolutions)
                geo_code = [geo_code operator_string];
            else
                geo_code = [geo_code ')'];
            end
        end
    end
    eidors_msg('@@@ called with "%s" returning.', operator_string, 4);
function geo_code = parse_geometry_cone(cone, operator_string)
    eidors_msg('@@@ called with "%s" starting.', operator_string, 4);
    if (~isstruct(cone) || isempty(cone))
        error('Parameter cone must be a valid structure.');
    else
        % Get number of cones.
        n_cones = numel(cone);
        % Get structure field names.
        field_names = fieldnames(cone);
        n_fields = numel(field_names);
        % Assign default values.
        top_radius      = 0.5*ones(1, n_cones);
        bottom_radius   = ones(1, n_cones);
        top_center      = [0;0;1]*ones(1, n_cones);
        bottom_center   = [0;0;0]*ones(1, n_cones);
        complement_flag = false(1, n_cones);
        % Parse all structure fields.
        for i = 1:n_fields
            switch (field_names{i})
                case 'top_radius'
                    top_radius = assign_radius(cone, n_cones, 'cone', field_names{i}, top_radius);
                case 'bottom_radius'
                    bottom_radius = assign_radius(cone, n_cones, 'cone', field_names{i}, bottom_radius);
                case {'top_center', 'top_centre'}
                    top_center = assign_point(cone, n_cones, 'cone', field_names{i}, top_center);
                case {'bottom_center', 'bottom_centre'}
                    bottom_center = assign_point(cone, n_cones, 'cone', field_names{i}, bottom_center);
                case 'complement_flag'
                    complement_flag = assign_flag(cone, n_cones, 'cone', field_names{i}, complement_flag);
                otherwise
                    error(['Field name ''%s'' is not valid for a cone.\Available field names for a cone are: ' ...
                           'bottom_center, bottom_radius, top_center, top_radius, and complement_flag.'], field_names{i});
            end
        end
        % Start geo code with an opening parenthesis.
        geo_code = '(';
        % Add geo code for each cone.
        for i = 1:n_cones
            if (complement_flag(i))
                geo_code = [geo_code 'not '];
            end
            n_vector = top_center(:,i) - bottom_center(:,i);
            geo_code = [geo_code sprintf('(cone(%g, %g, %g ; %g ; %g, %g, %g ; %g) and plane(%g, %g, %g ; %g, %g, %g) and plane(%g, %g, %g ; %g, %g, %g))', ...
                        bottom_center(:,i), bottom_radius(i), top_center(:,i), top_radius(i), bottom_center(:,i), -n_vector, top_center(:,i), n_vector)];
            if (i < n_cones)
                geo_code = [geo_code operator_string];
            else
                geo_code = [geo_code ')'];
            end
        end
    end
    eidors_msg('@@@ called with "%s" returning.', operator_string, 4);
function [geo_code,extra_code] = parse_geometry_cylinder(cylinder, operator_string)
    eidors_msg('@@@ called with "%s" starting.', operator_string, 4);
    if (~isstruct(cylinder) || isempty(cylinder))
        error('Parameter cylinder must be a valid structure.');
    else
        % Get number of cylinders.
        n_cylinders = numel(cylinder);
        % Get structure field names.
        field_names = fieldnames(cylinder);
        n_fields = numel(field_names);
        % Assign default values.
        radius          = ones(1, n_cylinders);
        top_center      = [0;0;1]*ones(1, n_cylinders);
        bottom_center   = [0;0;0]*ones(1, n_cylinders);
        complement_flag = false(1, n_cylinders);
        max_edge_length = inf(1,n_cylinders);;
        % Parse all structure fields.
        for i = 1:n_fields
            switch (field_names{i})
                case 'radius'
                    radius = assign_radius(cylinder, n_cylinders, 'cylinder', field_names{i}, radius);
                case {'top_center', 'top_centre'}
                    top_center = assign_point(cylinder, n_cylinders, 'cylinder', field_names{i}, top_center);
                case {'bottom_center', 'bottom_centre'}
                    bottom_center = assign_point(cylinder, n_cylinders, 'cylinder', field_names{i}, bottom_center);
                case 'complement_flag'
                    complement_flag = assign_flag(cylinder, n_cylinders, 'cylinder', field_names{i}, complement_flag);
                case 'max_edge_length'
                    for ii=1:length(cylinder);
                       mel = cylinder(ii).max_edge_length;
                       if isempty(mel)
                          max_edge_length(ii) = inf;
                       else
                          max_edge_length(ii) = mel;
                       end
                    end
                otherwise
                    error(['Field name ''%s'' is not valid for a cylinder!\nAvailable field names for a cylinder are: '...
                           'bottom_center, top_center, radius, max_edge_length and complement_flag.'], field_names{i});
            end
        end
        % Start geo code with an opening parenthesis.
        extra_code = '';
        geo_code = '(';
        % Add geo code for each cylinder.
        for i = 1:n_cylinders
            if (complement_flag(i))
                geo_code = [geo_code 'not '];
            end
            n_vector = top_center(:,i) - bottom_center(:,i);
            if isinf(max_edge_length(i))
               geo_code = [geo_code sprintf('(cylinder(%g, %g, %g ; %g, %g, %g ; %g) and plane(%g, %g, %g ; %g, %g, %g) and plane(%g, %g, %g ; %g, %g, %g))', ...
                           bottom_center(:,i), top_center(:,i), radius(i), bottom_center(:,i), -n_vector, top_center(:,i), n_vector)];
            else
               tmpvar   = sprintf('V%015d',round(1e15*rand));
               extra_code = [extra_code, sprintf( ...
                  'solid %s = cylinder(%g, %g, %g ; %g, %g, %g ; %g) -maxh=%g;\n', ...
                  tmpvar, bottom_center(:,i), top_center(:,i), radius(i), max_edge_length(i))];
               geo_code = [geo_code sprintf('((%s) and plane(%g, %g, %g ; %g, %g, %g) and plane(%g, %g, %g ; %g, %g, %g))', ...
                           tmpvar, bottom_center(:,i), -n_vector, top_center(:,i), n_vector)];
            end
            if (i < n_cylinders)
                geo_code = [geo_code operator_string];
            else
                geo_code = [geo_code ')'];
            end
        end
    end
    eidors_msg('@@@ called with "%s" returning.', operator_string, 4);
function geo_code = parse_geometry_ellipsoid(ellipsoid, operator_string)
    eidors_msg('@@@ called with "%s" starting.', operator_string, 4);
    if (~isstruct(ellipsoid) || isempty(ellipsoid))
        error('Parameter ellipsoid must be a valid structure.');
    else
        % Get number of ellipsoids.
        n_ellipsoids = numel(ellipsoid);
        % Get structure field names.
        field_names = fieldnames(ellipsoid);
        n_fields = numel(field_names);
        % Assign default values.
        axis_a          = [1;0;0]*ones(1, n_ellipsoids);
        axis_b          = [0;1;0]*ones(1, n_ellipsoids);
        axis_c          = [0;0;1]*ones(1, n_ellipsoids);
        center          = [0;0;0]*ones(1, n_ellipsoids);
        complement_flag = false(1, n_ellipsoids);
        % Parse all structure fields.
        for i = 1:n_fields
            switch (field_names{i})
                case {'center', 'centre'}
                    center = assign_point(ellipsoid, n_ellipsoids, 'ellipsoid', field_names{i}, center);
                case 'axis_a'
                    axis_a = assign_point(ellipsoid, n_ellipsoids, 'ellipsoid', field_names{i}, axis_a);
                case 'axis_b'
                    axis_b = assign_point(ellipsoid, n_ellipsoids, 'ellipsoid', field_names{i}, axis_b);
                case 'axis_c'
                    axis_c = assign_point(ellipsoid, n_ellipsoids, 'ellipsoid', field_names{i}, axis_c);
                case 'complement_flag'
                    complement_flag = assign_flag(ellipsoid, n_ellipsoids, 'ellipsoid', field_names{i}, complement_flag);
                otherwise
                     error(['Field name ''%s'' is not valid for an ellipsoid!\nAvailable field names for an ellipsoid are: '...
                           'center, axis_a, axis_b, axis_c, and complement_flag.'], field_names{i});
            end
        end
        % Start geo code with an opening parenthesis.
        geo_code = '(';
        % Add geo code for each ellipsoid.
        for i = 1:n_ellipsoids
            if (dot(axis_a(:,i), axis_b(:,i)) ~= 0)
                error('axis_a and axis_b have to be perpendicular for an ellipsoid.');
            elseif (dot(axis_a(:,i), axis_c(:,i)) ~= 0)
                error('axis_a and axis_c have to be perpendicular for an ellipsoid.');
            elseif (dot(axis_b(:,i), axis_c(:,i)) ~= 0)
                error('axis_b and axis_c have to be perpendicular for an ellipsoid.');
            end
            if (complement_flag(i))
                geo_code = [geo_code 'not '];
            end
            geo_code = [geo_code sprintf('ellipsoid(%g, %g, %g ; %g, %g, %g ; %g, %g, %g ; %g, %g, %g)', ...
                        center(:,i), axis_a(:, i), axis_b(:,i) , axis_c(:,i))];
            if (i < n_ellipsoids)
                geo_code = [geo_code operator_string];
            else
                geo_code = [geo_code ')'];
            end
        end
    end
    eidors_msg('@@@ called with "%s" returning.', operator_string, 4);
function geo_code = parse_geometry_elliptic_cylinder(elliptic_cylinder, operator_string)
    eidors_msg('@@@ called with "%s" starting.', operator_string, 4);
    if (~isstruct(elliptic_cylinder) || isempty(elliptic_cylinder))
        error('Parameter elliptic_cylinder must be a valid structure.');
    else
        % Get number of elliptic_cylinders.
        n_elliptic_cylinders = numel(elliptic_cylinder);
        % Get structure field names.
        field_names = fieldnames(elliptic_cylinder);
        n_fields = numel(field_names);
        % Assign default values.
        top_center      = [0;0;1]*ones(1, n_elliptic_cylinders);
        bottom_center   = [0;0;0]*ones(1, n_elliptic_cylinders);
        axis_a          = [1;0;0]*ones(1, n_elliptic_cylinders);
        axis_b          = [0;1;0]*ones(1, n_elliptic_cylinders);
        complement_flag = false(1, n_elliptic_cylinders);
        % Parse all structure fields.
        for i = 1:n_fields
1000             switch (field_names{i})
1001                 case {'top_center', 'top_centre'}
1002                     top_center = assign_point(elliptic_cylinder, n_elliptic_cylinders, 'elliptic_cylinder', field_names{i}, top_center);
1003                 case {'bottom_center', 'bottom_centre'}
1004                     bottom_center = assign_point(elliptic_cylinder, n_elliptic_cylinders, 'elliptic_cylinder', field_names{i}, bottom_center);
1005                 case 'axis_a'
1006                     axis_a = assign_point(elliptic_cylinder, n_elliptic_cylinders, 'elliptic_cylinder', field_names{i}, axis_a);
1007                 case 'axis_b'
1008                     axis_b = assign_point(elliptic_cylinder, n_elliptic_cylinders, 'elliptic_cylinder', field_names{i}, axis_b);
1009                 case 'complement_flag'
1010                     complement_flag = assign_flag(elliptic_cylinder, n_elliptic_cylinders, 'elliptic_cylinder', field_names{i}, complement_flag);
1011                 otherwise
1012                     error(['Field name ''%s'' is not valid for an elliptic cylinder!\nAvailable field names for an elliptic cylinder are: '...
1013                            'bottom_center, top_center, axis_a, axis_b, and complement_flag.'], field_names{i});
1014             end
1015         end
1016
1017         % Start geo code with an opening parenthesis.
1018         geo_code = '(';
1019
1020         % Add geo code for each cylinder.
1021         for i = 1:n_elliptic_cylinders
1022             if (complement_flag(i))
1023                 geo_code = [geo_code 'not '];
1024             end
1025
1026             central_axis = top_center(:,i) - bottom_center(:,i);
1027
1028             if (dot(axis_a(:,i), axis_b(:,i)) ~= 0)
1029                 error('axis_a and axis_b have to be perpendicular for an elliptic cylinder.');
1030             elseif (dot(axis_a(:,i), central_axis(:,i)) ~= 0)
1031                 error('axis_a and the central axis have to be perpendicular for an elliptic cylinder.');
1032             elseif (dot(axis_b(:,i), central_axis(:,i)) ~= 0)
1033                 error('axis_b and the central axis have to be perpendicular for an elliptic cylinder.');
1034             end
1035
1036             geo_code = [geo_code sprintf('(ellipticcylinder(%g, %g, %g ; %g, %g, %g ; %g, %g, %g) and plane(%g, %g, %g ; %g, %g, %g) and plane(%g, %g, %g ; %g, %g, %g))', ...
1037                         bottom_center(:,i), axis_a(:,i), axis_b(:,i), bottom_center(:,i), -central_axis, top_center(:,i), central_axis)];
1038
1039             if (i < n_elliptic_cylinders)
1040                 geo_code = [geo_code operator_string];
1041             else
1042                 geo_code = [geo_code ')'];
1043             end
1044         end
1045     end
1046
1047     eidors_msg('@@@ called with "%s" returning.', operator_string, 4);
1048
1049 function geo_code = parse_geometry_half_space(half_space, operator_string)
1050
1051     eidors_msg('@@@ called with "%s" starting.', operator_string, 4);
1052
1053     if (~isstruct(half_space) || isempty(half_space))
1054         error('Parameter half_space must be a valid structure.');
1055     else
1056         % Get number of half_spaces.
1057         n_half_spaces = numel(half_space);
1058
1059         % Get structure field names.
1060         field_names = fieldnames(half_space);
1061         n_fields = numel(field_names);
1062
1063         % Assign default values.
1064         point           = [0;0;0]*ones(1, n_half_spaces);
1065         outward_normal_vector  = [0;0;1]*ones(1, n_half_spaces);
1066         complement_flag = false(1, n_half_spaces);
1067
1068         % Parse all structure fields.
1069         for i = 1:n_fields
1070             switch (field_names{i})
1071                 case 'point'
1072                     point = assign_point(half_space, n_half_spaces, 'half_space', field_names{i}, point);
1073                 case 'outward_normal_vector'
1074                     outward_normal_vector = assign_point(half_space, n_half_spaces, 'half_space', field_names{i}, outward_normal_vector);
1075                 case 'complement_flag'
1076                     complement_flag = assign_flag(half_space, n_half_spaces, 'half_space', field_names{i}, complement_flag);
1077                 otherwise
1078                     error(['Field name ''%s'' is not valid for a half_space!\Available field names for a half_space are: ' ...
1079                            'point, outward_normal_vector, and complement_flag.'], field_names{i});
1080             end
1081         end
1082
1083         % Start geo code with an opening parenthesis.
1084         geo_code = '(';
1085
1086         % Add geo code for each half_space.
1087         for i = 1:n_half_spaces
1088             if (complement_flag(i))
1089                 geo_code = [geo_code 'not '];
1090             end
1091
1092             geo_code = [geo_code sprintf('plane(%g, %g, %g ; %g, %g, %g)', ...
1093                         point(:,i), outward_normal_vector(:,i))];
1094
1095             if (i < n_half_spaces)
1096                 geo_code = [geo_code operator_string];
1097             else
1098                 geo_code = [geo_code ')'];
1099             end
1100         end
1101     end
1102
1103     eidors_msg('@@@ called with "%s" returning.', operator_string, 4);
1104
1105 function geo_code = parse_geometry_ortho_brick(ortho_brick, operator_string)
1106
1107     eidors_msg('@@@ called with "%s" starting.', operator_string, 4);
1108
1109     if (~isstruct(ortho_brick) || isempty(ortho_brick))
1110         error('Parameter ortho_brick must be a valid structure.');
1111     else
1112         % Get number of ortho_bricks.
1113         n_ortho_bricks = numel(ortho_brick);
1114
1115         % Get structure field names.
1116         field_names = fieldnames(ortho_brick);
1117         n_fields = numel(field_names);
1118
1119         % Assign default values.
1120         opposite_corner_a = [0;0;0]*ones(1, n_ortho_bricks);
1121         opposite_corner_b = [1;1;1]*ones(1, n_ortho_bricks);
1122         complement_flag   = zeros(1, n_ortho_bricks);
1123
1124         % Parse all structure fields.
1125         for i = 1:n_fields
1126             switch (field_names{i})
1127                 case {'opposite_corner_a'}
1128                     opposite_corner_a = assign_point(ortho_brick, n_ortho_bricks, 'ortho_brick', field_names{i}, opposite_corner_a);
1129                 case {'opposite_corner_b'}
1130                     opposite_corner_b = assign_point(ortho_brick, n_ortho_bricks, 'ortho_brick', field_names{i}, opposite_corner_b);
1131                 case 'complement_flag'
1132                     complement_flag = assign_flag(ortho_brick, n_ortho_bricks, 'ortho_brick', field_names{i}, complement_flag);
1133                 otherwise
1134                     error(['Field name "%s" is not allowed for an ortho_brick!\nAllowed field names for an ortho_brick are: ' ...
1135                            'opposite_corner_a, opposite_corner_b, and complement_flag.'], field_names{i});
1136             end
1137         end
1138
1139         % Start geo code with an opening parenthesis.
1140         geo_code = '(';
1141
1142         % Add geo code for each ortho_brick.
1143         for i = 1:n_ortho_bricks
1144             if (complement_flag(i))
1145                 geo_code = [geo_code 'not '];
1146             end
1147
1148             geo_code = [geo_code sprintf('orthobrick(%g, %g, %g ; %g, %g, %g)', ...
1149                         min([opposite_corner_a(:, i) opposite_corner_b(:, i)], [], 2), ...
1150                         max([opposite_corner_a(:, i) opposite_corner_b(:, i)], [], 2))];
1151
1152             if (i < n_ortho_bricks)
1153                 geo_code = [geo_code operator_string];
1154             else
1155                 geo_code = [geo_code ')'];
1156             end
1157         end
1158     end
1159
1160     eidors_msg('@@@ called with "%s" returning.', operator_string, 4);
1161
1162 function geo_code = parse_geometry_parallelepiped(parallelepiped, operator_string)
1163
1164     eidors_msg('@@@ called with "%s" starting.', operator_string, 4);
1165
1166     if (~isstruct(parallelepiped) || isempty(parallelepiped))
1167         error('Parameter parallelepiped must be a valid structure.');
1168     else
1169         % Get number of parallelepiped.
1170         n_parallelepipeds = numel(parallelepiped);
1171
1172         % Get structure field names.
1173         field_names = fieldnames(parallelepiped);
1174         n_fields = numel(field_names);
1175
1176         % Assign default values.
1177         vertex          = [0;0;0]*ones(1, n_parallelepipeds);
1178         vector_a        = [1;0;0]*ones(1, n_parallelepipeds);
1179         vector_b        = [0;1;0]*ones(1, n_parallelepipeds);
1180         vector_c        = [0;0;1]*ones(1, n_parallelepipeds);
1181         complement_flag = zeros(1, n_parallelepipeds);
1182
1183         % Parse all structure fields.
1184         for i = 1:n_fields
1185             switch (field_names{i})
1186                 case 'vertex'
1187                     vertex = assign_point(parallelepiped, n_parallelepipeds, 'parallelepiped', field_names{i}, vertex);
1188                 case 'vector_a'
1189                     vector_a = assign_point(parallelepiped, n_parallelepipeds, 'parallelepiped', field_names{i}, vector_a);
1190                 case 'vector_b'
1191                     vector_b = assign_point(parallelepiped, n_parallelepipeds, 'parallelepiped', field_names{i}, vector_b);
1192                 case 'vector_c'
1193                     vector_c = assign_point(parallelepiped, n_parallelepipeds, 'parallelepiped', field_names{i}, vector_c);
1194                 case 'complement_flag'
1195                     complement_flag = assign_flag(parallelepiped, n_parallelepipeds, 'parallelepiped', field_names{i}, complement_flag);
1196                 otherwise
1197                     error(['Field name "%s" is not allowed for a parallelepiped!\nAllowed field names for a parallelepiped are: ' ...
1198                            'vertex, vector_a, vector_b, vector_c, and complement_flag.'], field_names{i});
1199             end
1200         end
1201
1202         % Start geo code with an opening parenthesis.
1203         geo_code = '(';
1204
1205         % Add geo code for each parallelepiped.
1206         for i = 1:n_parallelepipeds
1207             if (complement_flag(i))
1208                 geo_code = [geo_code 'not '];
1209             end
1210
1211             % Make sure all vectors are not coplanar.
1212             if (abs(dot(vector_a(:,i), cross(vector_b(:,i), vector_c(:,i)))) < eps)
1213                 error('parallelepiped(%d) description includes coplanar vectors.', i);
1214             end
1215
1216             % Compute opposite vertex.
1217             opposite_vertex = vertex(:,i) + vector_a(:,i) + vector_b(:,i) + vector_c(:,i);
1218
1219             % Compute normal vectors.
1220             n_vector_ab = cross(vector_a(:,i), vector_b(:,i));
1221             n_vector_ac = cross(vector_a(:,i), vector_c(:,i));
1222             n_vector_bc = cross(vector_b(:,i), vector_c(:,i));
1223
1224             % Check normal vectors directions.
1225             if (dot(n_vector_ab, vector_c(:,i)) < 0)
1226                 n_vector_ab = -n_vector_ab;
1227             end
1228             if (dot(n_vector_ac, vector_b(:,i)) < 0)
1229                 n_vector_ac = -n_vector_ac;
1230             end
1231             if (dot(n_vector_bc, vector_a(:,i)) < 0)
1232                 n_vector_bc = -n_vector_bc;
1233             end
1234
1235             geo_code = [geo_code sprintf(['(plane(%g, %g, %g ; %g, %g, %g) and' ...
1236                                           ' plane(%g, %g, %g ; %g, %g, %g) and' ...
1237                                           ' plane(%g, %g, %g ; %g, %g, %g) and' ...
1238                                           ' plane(%g, %g, %g ; %g, %g, %g) and' ...
1239                                           ' plane(%g, %g, %g ; %g, %g, %g) and' ...
1240                                           ' plane(%g, %g, %g ; %g, %g, %g))'], ...
1241                         vertex(:,i), -n_vector_ab, ...
1242                         vertex(:,i), -n_vector_ac, ...
1243                         vertex(:,i), -n_vector_bc, ...
1244                         opposite_vertex, n_vector_ab, ...
1245                         opposite_vertex, n_vector_ac, ...
1246                         opposite_vertex, n_vector_bc)];
1247
1248             if (i < n_parallelepipeds)
1249                 geo_code = [geo_code operator_string];
1250             else
1251                 geo_code = [geo_code ')'];
1252             end
1253         end
1254     end
1255
1256     eidors_msg('@@@ called with "%s" returning.', operator_string, 4);
1257
1258 function geo_code = parse_geometry_sphere(sphere, operator_string)
1259
1260     eidors_msg('@@@ called with "%s" starting.', operator_string, 4);
1261
1262     if (~isstruct(sphere) || isempty(sphere))
1263         error('Parameter sphere must be a valid structure.');
1264     else
1265         % Get number of spheres.
1266         n_spheres = numel(sphere);
1267
1268         % Get structure field names.
1269         field_names = fieldnames(sphere);
1270         n_fields = numel(field_names);
1271
1272         % Assign default values.
1273         radius          = ones(1, n_spheres);
1274         center          = [0;0;0]*ones(1, n_spheres);
1275         complement_flag = false(1, n_spheres);
1276
1277         % Parse all structure fields.
1278         for i = 1:n_fields
1279             switch (field_names{i})
1280                 case {'center', 'centre'}
1281                     center = assign_point(sphere, n_spheres, 'sphere', field_names{i}, center);
1282                 case 'radius'
1283                     radius = assign_radius(sphere, n_spheres, 'sphere', field_names{i}, radius);
1284                 case 'complement_flag'
1285                     complement_flag = assign_flag(sphere, n_spheres, 'sphere', field_names{i}, complement_flag);
1286                 otherwise
1287                     error(['Field name ''%s'' is not valid for a sphere.\nAvailable field names for a sphere are: ' ...
1288                            'center, radius, and complement_flag.'], field_names{i});
1289             end
1290         end
1291
1292         % Start geo code with an opening parenthesis.
1293         geo_code = '(';
1294
1295         % Add geo code for each sphere.
1296         for i = 1:n_spheres
1297             if (complement_flag(i))
1298                 geo_code = [geo_code 'not '];
1299             end
1300
1301             geo_code = [geo_code sprintf('sphere(%g, %g, %g ; %g)', ...
1302                         center(:,i), radius(i))];
1303
1304             if (i < n_spheres)
1305                 geo_code = [geo_code operator_string];
1306             else
1307                 geo_code = [geo_code ')'];
1308             end
1309         end
1310     end
1311
1312     eidors_msg('@@@ called with "%s" returning.', operator_string, 4);
1313
1314 function write_geo_file(geo_fn, body_solid_code, electrode_solid_code, body_extra_code, electrode_extra_code, body_extra_param, electrode_extra_param)
1315
1316     % Open geo file for writing.
1317     fid = fopen(geo_fn, 'w');
1318
1319     if (fid == -1)
1320         error('Unable to open file %s for writing.', geo_fn);
1321     end
1322
1323     % Write header for geo file.
1324     fprintf(fid, '#Automatically generated by ng_mk_geometric_models\n\n');
1325     fprintf(fid, 'algebraic3d\n\n');
1326
1327     % Assemble a string to represent the union of all bodies.
1328     total_body_solid = '(';
1329
1330     for i = 1:numel(body_solid_code)
1331         total_body_solid = [total_body_solid body_extra_param{i}.name];
1332
1333         if (i < numel(body_solid_code))
1334             total_body_solid = [total_body_solid ' or '];
1335         else
1336             total_body_solid = [total_body_solid ')'];
1337         end
1338     end
1339
1340     % Assemble a string to represent the union of all electrodes entering the body.
1341     total_electrode_solid = '(';
1342     n_total_electrode_solid = 0;
1343
1344     for i = 1:numel(electrode_solid_code)
1345         if (electrode_extra_param{i}.enter_body_flag)
1346             if (n_total_electrode_solid > 0)
1347                 total_electrode_solid = [total_electrode_solid ' or '];
1348             end
1349             total_electrode_solid = [total_electrode_solid electrode_extra_param{i}.name];
1350             n_total_electrode_solid = n_total_electrode_solid + 1;
1351         end
1352     end
1353     total_electrode_solid = [total_electrode_solid ')'];
1354
1355     % Write body_extra_code and electrode_extra_code in geo file
1356     for i = 1:numel(body_extra_code)
1357         if (~isempty(body_extra_code{i}))
1358             fprintf(fid, body_extra_code{i});
1359         end
1360     end
1361     for i = 1:numel(electrode_extra_code)
1362         if (~isempty(electrode_extra_code{i}))
1363             fprintf(fid, electrode_extra_code{i});
1364         end
1365     end
1366     fprintf(fid, '\n');
1367
1368     % Write electrode solids that enter the body in geo file.
1369     for i = 1:numel(electrode_solid_code)
1370         if (~isempty(electrode_solid_code{i}) && electrode_extra_param{i}.enter_body_flag)
1371             fprintf(fid, 'solid %s = %s;\n\n', electrode_extra_param{i}.name, electrode_solid_code{i});
1372         end
1373     end
1374
1375     % Write body solids in geo file.
1376     for i = 1:numel(body_solid_code)
1377         if (n_total_electrode_solid == 0)
1378             fprintf(fid, 'solid %s = %s;\n\n', body_extra_param{i}.name, body_solid_code{i});
1379         else
1380             fprintf(fid, 'solid %s = not %s and %s;\n\n', body_extra_param{i}.name, total_electrode_solid, body_solid_code{i});
1381         end
1382     end
1383
1384     % Write electrode solids that do not enter the body in geo file.
1385     for i = 1:numel(electrode_solid_code)
1386         if (~isempty(electrode_solid_code{i}) && ~electrode_extra_param{i}.enter_body_flag)
1387             fprintf(fid, 'solid %s = not %s and %s;\n\n', electrode_extra_param{i}.name, total_body_solid, electrode_solid_code{i});
1388         end
1389     end
1390
1391     % Write electrode tlos in geo file.
1392     for i = 1:numel(electrode_solid_code)
1393         if (~isempty(electrode_solid_code{i}))
1394             if (isinf(electrode_extra_param{i}.max_edge_length))
1395                 fprintf(fid, 'tlo %s -col=[1,0,0] -material=%s;\n', electrode_extra_param{i}.name, electrode_extra_param{i}.name);
1396             else
1397                 fprintf(fid, 'tlo %s -col=[1,0,0] -material=%s -maxh=%g;\n', electrode_extra_param{i}.name, electrode_extra_param{i}.name, electrode_extra_param{i}.max_edge_length);
1398             end
1399         end
1400     end
1401
1402     % Assume the last object is the main one
1403     % This code is needed to make sure the main object does
1404     % not contain the others
1405     mainobj = 'MainNetgenObject';
1406     fprintf(fid, 'solid %s = %s ', mainobj, body_extra_param{end}.name);
1407     for i= 1:numel(body_solid_code)-1
1408        fprintf(fid, 'and (not %s)', body_extra_param{i}.name);
1409     end
1410     fprintf(fid, ';\n');
1411     body_extra_param{end}.name = mainobj; % rename it for following code
1412
1413     % Write body tlos in geo file.
1414     for i = 1:numel(body_solid_code)
1415         if (isinf(body_extra_param{i}.max_edge_length))
1416             fprintf(fid, 'tlo %s -col=[0,1,0] -material=%s;\n', body_extra_param{i}.name, body_extra_param{i}.name);
1417         else
1418             fprintf(fid, 'tlo %s -col=[0,1,0] -material=%s -maxh=%g;\n', body_extra_param{i}.name, body_extra_param{i}.name, body_extra_param{i}.max_edge_length);
1419         end
1420     end
1421
1422     % Close file.
1423     fclose(fid);
1424
1425 function mat = read_mat_from_file(fid, nrows, ncols)
1426     mat = fscanf(fid, '%g', [ncols, nrows])';
1427
1428     % Skip to next line.
1429     if (~isempty(fgetl(fid)))
1430         error('Last line was only partialy read.');
1431     end
1432
1433 function fmdl = read_vol_file(vol_fn, electrode_extra_param)
1434
1435     % Open file for reading.
1436     fid = fopen(vol_fn, 'r');
1437
1438     if (fid == -1)
1439         error('Unable to open file %s for reading.', vol_fn);
1440     end
1441
1442     % Read a first line in vol file.
1443     line = fgetl(fid);
1444
1445     % While no EOF or "endmesh" keyword is found.
1446     while (ischar(line) && ~strcmp(line, 'endmesh'))
1447
1448         % Parse every line if not comment or empty line
1449         if (~isempty(line) && line(1) ~= '#') % Supposing '#' is always the first character of a comment line.
1450             switch(line)
1451                 case 'mesh3d'   % Nothing to do.
1452                 case 'dimension'
1453                     dimension = read_mat_from_file(fid, 1, 1);
1454                     if (dimension ~= 3)
1455                         error('unknown dimension %g in vol file.', dimension);
1456                     end
1457                 case 'geomtype'
1458                     geomtype = read_mat_from_file(fid, 1, 1);
1459                     if (geomtype ~= 0)
1460                         error('unknown %g geomtype in vol file.', geomtype);
1461                     end
1462                 case 'surfaceelements'
1463                     % # surfnr    bcnr   domin  domout      np      p1      p2      p3
1464                     n_surface_elements = read_mat_from_file(fid, 1, 1);
1465                     if (n_surface_elements)
1466                         surface_elements   = read_mat_from_file(fid, n_surface_elements, 8);
1467                     else
1468                         error('vol file contains no surface elements. There is probably something wrong with the provided geometry description.');
1469                     end
1470                 case 'volumeelements'
1471                     % #  matnr      np      p1      p2      p3      p4
1472                     n_volume_elements = read_mat_from_file(fid, 1, 1);
1473                     if (n_volume_elements)
1474                         volume_elements   = read_mat_from_file(fid, n_volume_elements, 6);
1475                     else
1476                         error('vol file contains no volume elements. There is probably something wrong with the provided geometry description.');
1477                     end
1478                 case 'edgesegmentsgi2'
1479                     % # surfid  0   p1   p2   trignum1    trignum2   domin/surfnr1    domout/surfnr2   ednr1   dist1   ednr2   dist2
1480                     n_edge_segments_sgi2 = read_mat_from_file(fid, 1, 1);
1481                     edge_segments_sgi2   = read_mat_from_file(fid, n_edge_segments_sgi2, 12);
1482                 case 'points'
1483                     % #          X             Y             Z
1484                     n_points = read_mat_from_file(fid, 1, 1);
1485                     if (n_points)
1486                         points   = read_mat_from_file(fid, n_points, 3);
1487                     else
1488                         error('vol file contains no points. There is probably something wrong with the provided geometry description.');
1489                     end
1490                 case 'materials'
1491                     n_materials = read_mat_from_file(fid, 1, 1);
1492                     if (n_materials)
1493                         materials   = cell(n_materials, 2);
1494                         % Read and parse each material line.
1495                         for i = 1:n_materials
1496                             material_line = fgetl(fid);
1497                             sscanf_result = sscanf(material_line, '%g%c%s')';
1498                             materials{i, 1} = sscanf_result(1);
1499                             materials{i, 2} = char(sscanf_result(3:end));
1500                         end
1501                     else
1502                         error('vol file contains no materials. There is probably something wrong with the provided geometry description.');
1503                     end
1504                 case 'face_colours'
1505                     % #   Surfnr     Red     Green     Blue
1506                     n_face_colours = read_mat_from_file(fid, 1, 1);
1507                     face_colours   = read_mat_from_file(fid, n_face_colours, 4);
1508                 otherwise
1509                     error('unknown "%s" line in vol file.', line);
1510             end
1511         end
1512
1513         % Read next line in vol file.
1514         line = fgetl(fid);
1515     end
1516
1517     % Close file.
1518     fclose(fid);
1519
1520     if (~exist('points', 'var'))
1521         error('Point description is missing from vol file.');
1522     end
1523
1524     if (~exist('volume_elements', 'var'))
1525         error('Volume element description is missing from vol file.');
1526     end
1527
1528     if (~exist('surface_elements', 'var'))
1529         error('Surface element description is missing from vol file.');
1530     end
1531
1532     if (~exist('materials', 'var'))
1533         error('Material description is missing from vol file.');
1534     end
1535
1536     % Find electrode and body material indices.
1537     electrode_material = [];
1538     for i = 1:n_materials
1539         material_name   = materials{i, 2};
1540         material_number = materials{i, 1};
1541
1542 %         if (strncmp(material_name, 'electrode', 9))
1543 %             % Extract electrode number from material_name
1544 %             electrode_number = str2double(material_name(10:end));
1545 %             electrode_material(electrode_number) = material_number;
1546 %         end
1547         for j = 1:numel(electrode_extra_param)
1548             if (strcmp(material_name, electrode_extra_param{j}.name))
1549                 electrode_material(j) = material_number;
1550             end
1551         end
1552     end
1553
1554     % Remove electrode material if necessary
1555     original_n_nodes     = size(points, 1);
1556     original_n_elements  = size(volume_elements, 1);
1557     original_n_surfaces  = size(surface_elements, 1);
1558     original_n_materials = size(materials, 1);
1559
1560     for i = 1:numel(electrode_material)
1561         if (~electrode_extra_param{i}.keep_material_flag)
1562             % Remove unwanted volume elements
1563             volume_elements(volume_elements(:, 1) == electrode_material(i), :) = [];
1564
1565             % Remove unwanted surface elements
1566             surface_elements(surface_elements(:, 3) == electrode_material(i) & ...
1567                              surface_elements(:, 4) == 0 | ...
1568                              surface_elements(:, 4) == electrode_material(i) & ...
1569                              surface_elements(:, 3) == 0, :) = [];
1570         end
1571     end
1572
1573     % Find nodes that are now unused.
1574     unused_nodes = true(1, size(points, 1));
1575     unused_nodes(volume_elements(:, 3:6))  = false;
1576     unused_nodes(surface_elements(:, 6:8)) = false;
1577
1578     % Remove unused points.
1579     points(unused_nodes, :) = [];
1580
1581     % Compute new node indices after node removal.
1582     new_node_index = (1:original_n_nodes) - cumsum(unused_nodes);
1583
1584     % Update node indices for surface and volume elements.
1585     surface_elements(:, 6:8) = new_node_index(surface_elements(:, 6:8));
1586     volume_elements(:, 3:6)  = new_node_index(volume_elements(:, 3:6));
1587
1588     % Find materials that are now unused.
1589     unused_materials = true(1, size(materials, 1));
1590     unused_materials(volume_elements(:, 1)) = false;
1591
1592     % Remove unused materials.
1593     materials(unused_materials, :) = [];
1594
1595     % Compute new material indices after material removal.
1596     new_material_index = (1:original_n_materials) - cumsum(unused_materials);
1597
1598     % Update material indices for volume elements.
1599     volume_elements(:, 1)  = new_material_index(volume_elements(:, 1));
1600
1601     eidors_msg('@@@ Removed %d nodes, %d elements, %d surfaces and %d materials', ...
1602         original_n_nodes     - size(points, 1), ...
1603         original_n_elements  - size(volume_elements, 1), ...
1604         original_n_surfaces  - size(surface_elements, 1), ...
1605         original_n_materials - size(materials, 1), 3);
1606
1607     % Assign mesh data to fmdl structures.
1608     fmdl.nodes            = points;
1609     fmdl.elems            = volume_elements(:, 3:6);
1610     fmdl.boundary         = surface_elements(:, 6:8);
1611     fmdl.boundary_numbers = surface_elements(:, 2);
1612     for i=1:max(volume_elements(:,1))
1613        fmdl.mat_idx{i}    = find(volume_elements(:, 1) == i);
1614     end
1615     fmdl.mat_name         = materials(:, 2);
1616
1617     % Find electrode surfaces and nodes.
1618     for i = 1:numel(electrode_material)
1619         % Find surfaces that are part of the electrodes.
1620         if (electrode_extra_param{i}.keep_material_flag)
1621             electrode_boundary = ...
1622                sort(find(surface_elements(:, 3) == 0 & ...
1623                          surface_elements(:, 4) == electrode_material(i) | ...
1624                          surface_elements(:, 4) == 0 & ...
1625                          surface_elements(:, 3) == electrode_material(i)))';
1626         else
1627             electrode_boundary = ...
1628                 sort(find(surface_elements(:, 3) == electrode_material(i) | ...
1629                           surface_elements(:, 4) == electrode_material(i)))';
1630         end
1631
1632         if (isempty(electrode_boundary))
1633             eidors_msg('WARNING: Electrode #%04d has been removed since it does not contact any body.', i, 2);
1634         else
1635             fmdl.electrode(i).boundary = electrode_boundary;
1636
1637             % Find nodes that are part of the electrodes.
1638             fmdl.electrode(i).nodes = ...
1639                 unique(fmdl.boundary(fmdl.electrode(i).boundary(:), :))';
1640
1641             % Assign default contact impedance.
1642             fmdl.electrode(i).z_contact = 0.01;
1643
1644             if (~isempty(electrode_extra_param{i}.name))
1645                 fmdl.electrode(i).name = electrode_extra_param{i}.name;
1646             end
1647         end
1648     end
1649
1650 function fmdl = complete_fmdl(fmdl, electrode_extra_param)
1651
1652     % Find center point of domain.
1653     domain_center  = (max(fmdl.nodes)-min(fmdl.nodes))/2 + min(fmdl.nodes);
1654     domain_centers = ones(size(fmdl.nodes, 1), 1)*domain_center;
1655
1656     % Find node closest to center for ground node.
1657     [unused, min_idx] = min(sum((fmdl.nodes - domain_centers).^2, 2));
1658     fmdl.gnd_node     = min_idx(1);
1659
1660     fmdl.np_fwd_solve.perm_sym = '{n}';
1661
1662     fmdl.name = 'ng_mk_geometric_models';
1663
1664     fmdl.solve=      'eidors_default';
1665     fmdl.jacobian=   'eidors_default';
1666     fmdl.system_mat= 'eidors_default';
1667
1668     fmdl.normalize_measurements = 0;
1669
1670     for i = 1:numel(electrode_extra_param)
1671         if (isfield(electrode_extra_param{i}, 'point'))
1672             % Find center point of domain.
1673             electrode_points = ones(size(fmdl.nodes, 1), 1)*electrode_extra_param{i}.point';
1674
1675             % Find node closest to the electrode point.
1676             [unused, min_idx]       = min(sum((fmdl.nodes - electrode_points).^2, 2));
1677             fmdl.electrode(i).nodes = min_idx(1);
1678             fmdl.electrode(i).boundary = [];
1679
1680             % Assign default contact impedance.
1681             fmdl.electrode(i).z_contact = 0.01;
1682         end
1683     end
1684
1685     fmdl = eidors_obj('fwd_model', fmdl);
1686
1687 function do_unit_test
1688     do_separate_internals_test
1689     do_combinations
1690
1691 % Ensure that objects don't overlap
1692 function do_separate_internals_test
1693     body_geometry{1}.sphere.radius     = 0.25;
1694     body_geometry{1}.sphere.center     = [0 0 0.5];
1695     body_geometry{1}.name              = 'Sphere';
1696     body_geometry{2}.cylinder.radius   = 1;
1697     body_geometry{2}.name              = 'Tank';
1698     n_elect = 16;
1699     th = linspace(0, 2*pi, n_elect+1); th(end) = [];
1700     for i = 1:n_elect
1701         electrode_geometry{i}.sphere.center = [cos(th(i)) sin(th(i)) 0.5];
1702         electrode_geometry{i}.sphere.radius = 0.1;
1703     end
1704     fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1705     imdl = fmdl; imdl.elems(fmdl.mat_idx{1},:) = [];
1706     omdl = fmdl; omdl.elems(fmdl.mat_idx{2},:) = [];
1707     c2f = mk_tet_c2f(omdl,imdl);
1708     unit_test_cmp('max overlap', max(c2f(:))     ,0,10*eps)
1709     unit_test_cmp('min overlap',-min(c2f(:))     ,0,10*eps)
1710     unit_test_cmp('mean overlap', mean(abs(c2f(:))),0,eps)
1711
1712 function do_combinations
1713     for tn = 1:do_test_number(0)
1714         eidors_msg('ng_mk_geometric_models: unit_test %02d', tn, 1);
1715         [fmdl, opts] = do_test_number(tn);
1716         subplot(1,3,1)
1717         show_fem(fmdl);
1718         title('show_fem', 'Interpreter', 'none', 'FontWeight', 'bold');
1719         subplot(1,3,2);
1720         show_fem_enhanced(fmdl, opts);
1721         title({'show_fem_enhanced'; '(default options)'}, 'Interpreter', 'none', 'FontWeight', 'bold');
1722         subplot(1,3,3);
1723         opts.edge.color = [0 0 1];
1724         opts.edge.width = 0;
1725         opts.edge.significant.color = [1 0 0];
1726         opts.edge.significant.width = 1.5;
1727         opts.edge.significant.viewpoint_dependent.color = [0 1 0];
1728         opts.edge.significant.viewpoint_dependent.width = 1.5;
1729         show_fem_enhanced(fmdl, opts);
1730         title({'show_fem_enhanced'; '(with some options)'}, 'Interpreter', 'none', 'FontWeight', 'bold');
1731         drawnow;
1732         %pause
1733     end
1734
1735 function [fmdl, opts] = do_test_number(tn)
1736     opts = struct;
1737     switch tn
1738         % Simple 3D cylinder. Radius = 1 with no electrodes
1739         case 1;
1740             body_geometry.cylinder = struct;
1741             fmdl = ng_mk_geometric_models(body_geometry);
1742         % Simple 3D cylinder. Radius = 1 with 16 spherical electrodes.
1743         case 2;
1744             body_geometry.cylinder = struct;
1745             n_elect = 16;
1746             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
1747             for i = 1:n_elect
1748                 electrode_geometry{i}.sphere.center = [cos(theta(i)) sin(theta(i)) 0.5];
1749                 electrode_geometry{i}.sphere.radius = 0.1;
1750             end
1751             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1752         % Simple 3D cylinder. Radius = 1 with 16 cylindrical electrodes.
1753         case 3;
1754             body_geometry.cylinder = struct;
1755             n_elect = 16;
1756             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
1757             for i = 1:n_elect
1758                 electrode_geometry{i}.cylinder.top_center    = [1.03*cos(theta(i)) 1.03*sin(theta(i)) 0.5];
1759                 electrode_geometry{i}.cylinder.bottom_center = [0.97*cos(theta(i)) 0.97*sin(theta(i)) 0.5];
1760                 electrode_geometry{i}.cylinder.radius = 0.1;
1761             end
1762             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1763         case 4;
1764             body_geometry.cylinder = struct;
1765             n_elect = 16;
1766             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
1767             for i = 1:n_elect
1768                 electrode_geometry{i}.cylinder.top_center    = [1.03*cos(theta(i)) 1.03*sin(theta(i)) 0.5];
1769                 electrode_geometry{i}.cylinder.bottom_center = [0.97*cos(theta(i)) 0.97*sin(theta(i)) 0.5];
1770                 electrode_geometry{i}.cylinder.radius = 0.1;
1771                 electrode_geometry{i}.keep_material_flag = 1;
1772             end
1773             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1774         case 5;
1775             body_geometry.cylinder = struct;
1776             n_elect = 16;
1777             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
1778             for i = 1:n_elect
1779                 electrode_geometry{i}.cylinder.top_center    = [1.03*cos(theta(i)) 1.03*sin(theta(i)) 0.5];
1780                 electrode_geometry{i}.cylinder.bottom_center = [0.97*cos(theta(i)) 0.97*sin(theta(i)) 0.5];
1781                 electrode_geometry{i}.cylinder.radius = 0.1;
1782                 electrode_geometry{i}.enter_body_flag = 1;
1783             end
1784             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1785         case 6;
1786             body_geometry.cylinder = struct;
1787             n_elect = 16;
1788             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
1789             for i = 1:n_elect
1790                 electrode_geometry{i}.cylinder.top_center    = [1.03*cos(theta(i)) 1.03*sin(theta(i)) 0.5];
1791                 electrode_geometry{i}.cylinder.bottom_center = [0.97*cos(theta(i)) 0.97*sin(theta(i)) 0.5];
1792                 electrode_geometry{i}.cylinder.radius = 0.1;
1793                 electrode_geometry{i}.keep_material_flag = 1;
1794                 electrode_geometry{i}.enter_body_flag = 1;
1795             end
1796             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1797         case 7;
1798             body_geometry.cylinder = struct;
1799             body_geometry.sphere.center = [0 0 1];
1800             n_elect = 16;
1801             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
1802             for i = 1:n_elect
1803                 electrode_geometry{i}.cylinder.top_center    = [1.03*cos(theta(i)) 1.03*sin(theta(i)) 0.5];
1804                 electrode_geometry{i}.cylinder.bottom_center = [0.97*cos(theta(i)) 0.97*sin(theta(i)) 0.5];
1805                 electrode_geometry{i}.cylinder.radius = 0.1;
1806             end
1807             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1808         case 8;
1809             body_geometry.cylinder  = struct;
1810             body_geometry.sphere(1) = struct;
1811             body_geometry.sphere(2).center = [0 0 1];
1812             n_elect = 16;
1813             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
1814             for i = 1:n_elect
1815                 electrode_geometry{i}.cylinder.top_center    = [1.03*cos(theta(i)) 1.03*sin(theta(i)) 0.5];
1816                 electrode_geometry{i}.cylinder.bottom_center = [0.97*cos(theta(i)) 0.97*sin(theta(i)) 0.5];
1817                 electrode_geometry{i}.cylinder.radius = 0.1;
1818             end
1819             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1820         case 9;
1821             body_geometry.intersection.cylinder(1) = struct;
1822             body_geometry.intersection.cylinder(2).radius     = 0.5;
1823             body_geometry.intersection.cylinder(2).complement_flag = 1;
1824             n_elect = 16;
1825             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
1826             for i = 1:n_elect
1827                 electrode_geometry{i}.cylinder.top_center    = [1.03*cos(theta(i)) 1.03*sin(theta(i)) 0.5];
1828                 electrode_geometry{i}.cylinder.bottom_center = [0.97*cos(theta(i)) 0.97*sin(theta(i)) 0.5];
1829                 electrode_geometry{i}.cylinder.radius = 0.1;
1830             end
1831             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1832         case 10;
1833             body_geometry.intersection(1).sphere(1).radius     = 0.5;
1834             body_geometry.intersection(1).sphere(1).center     = [0 0 2];
1835             body_geometry.intersection(1).sphere(1).complement_flag = 1;
1836             body_geometry.intersection(1).sphere(2).center     = [0 0 2];
1837             body_geometry.intersection(2).cylinder(1).top_center = [0 0 2];
1838             body_geometry.intersection(2).cylinder(2).radius     = 0.5;
1839             body_geometry.intersection(2).cylinder(2).top_center = [0 0 2];
1840             body_geometry.intersection(2).cylinder(2).complement_flag = 1;
1841             n_elect = 16;
1842             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
1843             for i = 1:n_elect
1844                 electrode_geometry{i}.cylinder.top_center    = [1.03*cos(theta(i)) 1.03*sin(theta(i)) 0.5];
1845                 electrode_geometry{i}.cylinder.bottom_center = [0.97*cos(theta(i)) 0.97*sin(theta(i)) 0.5];
1846                 electrode_geometry{i}.cylinder.radius = 0.1;
1847             end
1848             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1849         case 11;
1850             body_geometry.intersection.union(1).sphere.radius = 0.5;
1851             body_geometry.intersection.union(1).sphere.center = [0 0 2];
1852             body_geometry.intersection.union(1).cylinder.radius = 0.5;
1853             body_geometry.intersection.union(1).cylinder.top_center = [0 0 2];
1854             body_geometry.intersection.union(1).complement_flag = 1;
1855             body_geometry.intersection.union(2).sphere.center = [0 0 2];
1856             body_geometry.intersection.union(2).cylinder.top_center = [0 0 2];
1857             n_elect = 16;
1858             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
1859             for i = 1:n_elect
1860                 electrode_geometry{i}.cylinder.top_center    = [1.03*cos(theta(i)) 1.03*sin(theta(i)) 0.5];
1861                 electrode_geometry{i}.cylinder.bottom_center = [0.97*cos(theta(i)) 0.97*sin(theta(i)) 0.5];
1862                 electrode_geometry{i}.cylinder.radius = 0.1;
1863             end
1864             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1865         case 12;
1866             body_geometry.cone = struct;
1867             n_elect = 16;
1868             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
1869             for i = 1:n_elect
1870                 electrode_geometry{i}.cylinder.top_center    = [0.85*cos(theta(i)) 0.85*sin(theta(i)) 0.5];
1871                 electrode_geometry{i}.cylinder.bottom_center = [0.65*cos(theta(i)) 0.65*sin(theta(i)) 0.5];
1872                 electrode_geometry{i}.cylinder.radius = 0.1;
1873             end
1874             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1875         case 13;
1876             body_geometry.cone = struct;
1877             n_elect = 16;
1878             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
1879             for i = 1:n_elect
1880                 electrode_geometry{i}.sphere.center = [0.75*cos(theta(i)) 0.75*sin(theta(i)) 0.5];
1881                 electrode_geometry{i}.sphere.radius = 0.1;
1882             end
1883             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1884         case 14;
1885             body_geometry.cone(1).top_center = [0 0 1.5];
1886             body_geometry.cone(1).bottom_center = [0 0 0.5];
1887             body_geometry.cone(2).top_center = [0 0 -1.5];
1888             body_geometry.cone(2).bottom_center = [0 0 -0.5];
1889             body_geometry.cylinder.top_center    = [0, 0, 0.5];
1890             body_geometry.cylinder.bottom_center = [0, 0, -0.5];
1891             n_elect = 16;
1892             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
1893             for i = 1:n_elect
1894                 electrode_geometry{i}.sphere.center = [0.75*cos(theta(i)) 0.75*sin(theta(i)) 1.0];
1895                 electrode_geometry{i}.sphere.radius = 0.1;
1896                 electrode_geometry{i + n_elect}.sphere.center = [cos(theta(i)) sin(theta(i)) 0];
1897                 electrode_geometry{i + n_elect}.sphere.radius = 0.15;
1898                 electrode_geometry{i + 2*n_elect}.sphere.center = [0.75*cos(theta(i)) 0.75*sin(theta(i)) -1.0];
1899                 electrode_geometry{i + 2*n_elect}.sphere.radius = 0.1;
1900             end
1901             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1902             opts.edge.significant.angle = 15;
1903         case 15
1904             body_geometry.ortho_brick = struct;
1905             fmdl = ng_mk_geometric_models(body_geometry);
1906         case 16
1907             body_geometry.intersection.ortho_brick.opposite_corner_a = [0 0 0];
1908             body_geometry.intersection.ortho_brick.opposite_corner_b = [5 5 4];
1909             for i = 1:4;
1910                 for j = 1:4;
1911                     body_geometry.intersection.cylinder(i,j).radius = 0.15;
1912                     body_geometry.intersection.cylinder(i,j).top_center = [i, j, 4];
1913                     body_geometry.intersection.cylinder(i,j).bottom_center = [i, j, 2];
1914                     body_geometry.intersection.cylinder(i,j).complement_flag = 1;
1915                 end;
1916             end;
1917             fmdl = ng_mk_geometric_models(body_geometry);
1918         case 17
1919             body_geometry.intersection.ortho_brick.opposite_corner_a = [0 0 0];
1920             body_geometry.intersection.ortho_brick.opposite_corner_b = [5 5 4];
1921             for i = 1:4;
1922                 for j = 1:4;
1923                     body_geometry.intersection.cylinder(i, j).radius = 0.15;
1924                     body_geometry.intersection.cylinder(i, j).top_center    = [i, j, 4];
1925                     body_geometry.intersection.cylinder(i, j).bottom_center = [i, j, 2];
1926                     body_geometry.intersection.cylinder(i, j).complement_flag = 1;
1927                     electrode_geometry{i, j, 1}.cylinder.radius        = 0.2;
1928                     electrode_geometry{i, j, 1}.cylinder.top_center    = [i, j, 3.1];
1929                     electrode_geometry{i, j, 1}.cylinder.bottom_center = [i, j, 2.9];
1930                     electrode_geometry{i, j, 2}.cylinder.radius        = 0.2;
1931                     electrode_geometry{i, j, 2}.cylinder.top_center    = [i, j, 2.2];
1932                     electrode_geometry{i, j, 2}.cylinder.bottom_center = [i, j, 2.0];
1933                 end;
1934             end;
1935             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
1936         case 18
1937             body_geometry.parallelepiped  = struct;
1938             body_geometry.max_edge_length = 0.15;
1939             fmdl = ng_mk_geometric_models(body_geometry);
1940         case 19
1941             body_geometry.parallelepiped.vertex   = [ 0;  0;  0];
1942             body_geometry.parallelepiped.vector_a = [ 1;  1;  0];
1943             body_geometry.parallelepiped.vector_b = [ 0;  1;  1];
1944             body_geometry.parallelepiped.vector_c = [ 1;  0;  1];
1945             body_geometry.max_edge_length = 0.15;
1946             fmdl = ng_mk_geometric_models(body_geometry);
1947         case 20
1948             body_geometry.intersection.ortho_brick.opposite_corner_a = [-15, -15, 0];
1949             body_geometry.intersection.ortho_brick.opposite_corner_b = [15, 15, 5];
1950             body_geometry.intersection.half_space.point = [0, 0, 5];
1951             body_geometry.intersection.half_space.outward_normal_vector = [-1, -1, 5];
1952
1953             fmdl = ng_mk_geometric_models(body_geometry);
1954         case 21
1955             body_geometry.ellipsoid.axis_a = [1 0 0];
1956             body_geometry.ellipsoid.axis_b = [0 2 0];
1957             body_geometry.ellipsoid.axis_c = [0 0 3];
1958             fmdl = ng_mk_geometric_models(body_geometry);
1959         case 22
1960             body_geometry.ellipsoid.axis_a = [1 0 0];
1961             body_geometry.ellipsoid.axis_b = [0 1 1];
1962             body_geometry.ellipsoid.axis_c = [0 -2 2];
1963             fmdl = ng_mk_geometric_models(body_geometry);
1964         case 23
1965             body_geometry.elliptic_cylinder.top_center = [0, 0, 10];
1966             body_geometry.elliptic_cylinder.bottom_center = [0, 0, 0];
1967             body_geometry.elliptic_cylinder.axis_a = [1 0 0];
1968             body_geometry.elliptic_cylinder.axis_b = [0 2 0];
1969             fmdl = ng_mk_geometric_models(body_geometry);
1970         case 24
1971             body_geometry.elliptic_cylinder.top_center = [0, 5, 5];
1972             body_geometry.elliptic_cylinder.bottom_center = [0, 0, 0];
1973             body_geometry.elliptic_cylinder.axis_a = [1 0 0];
1974             body_geometry.elliptic_cylinder.axis_b = [0 -2 2];
1975             fmdl = ng_mk_geometric_models(body_geometry);
1976         case 25
1977             body_geometry.body_of_revolution = struct;
1978             body_geometry.max_edge_length = 0.15;
1979             fmdl = ng_mk_geometric_models(body_geometry);
1980         case 26
1981             body_geometry.body_of_revolution.points   = [1 1; 1 2; 2 1.5; 2 1];
1982             body_geometry.body_of_revolution.segments = [1 2; 2 3; 3 4; 4 1];
1983             body_geometry.max_edge_length = 0.15;
1984             fmdl = ng_mk_geometric_models(body_geometry);
1985         case 27
1986             n_points = 24;
1987             theta = linspace(0, 2*pi, n_points+1)'; theta(end) = [];
1988             body_geometry.body_of_revolution.points   = 2 + [sin(theta) cos(theta)];
1989             body_geometry.body_of_revolution.segments = [(1:n_points)' [(2:n_points) 1]'];
1990             body_geometry.max_edge_length = 0.15;
1991             fmdl = ng_mk_geometric_models(body_geometry);
1992         case 28
1993             n_points = 24;
1994             theta = linspace(0, 2*pi, n_points+1)'; theta(end) = [];
1995             body_geometry.body_of_revolution.points   = 2 + [sin(theta) cos(theta)];
1996             body_geometry.body_of_revolution.segments = [(1:2:n_points)' (2:2:n_points)' [(3:2:n_points) 1]'];
1997             body_geometry.max_edge_length = 0.15;
1998             fmdl = ng_mk_geometric_models(body_geometry);
1999         case 29
2000             body_geometry{1}.cylinder(1).radius        = 0.5;
2001             body_geometry{1}.cylinder(1).top_center    = [0 0 0.75];
2002             body_geometry{1}.cylinder(1).bottom_center = [0 0 0.25];
2003             body_geometry{1}.name                      = 'Object';
2004             body_geometry{2}.cylinder(2).radius        = 1;
2005             body_geometry{2}.name                      = 'Tank';
2006             n_elect = 16;
2007             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
2008             for i = 1:n_elect
2009                 electrode_geometry{i}.cylinder.top_center    = [1.03*cos(theta(i)) 1.03*sin(theta(i)) 0.5];
2010                 electrode_geometry{i}.cylinder.bottom_center = [0.97*cos(theta(i)) 0.97*sin(theta(i)) 0.5];
2011                 electrode_geometry{i}.cylinder.radius = 0.1;
2012             end
2013             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
2014         case 30
2015             body_geometry{1}.sphere.radius     = 0.25;
2016             body_geometry{1}.sphere.center     = [0 0 0.5];
2017             body_geometry{1}.name              = 'Sphere';
2018             body_geometry{2}.cylinder.radius   = 1;
2019             body_geometry{2}.name              = 'Tank';
2020             n_elect = 16;
2021             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
2022             for i = 1:n_elect
2023                 electrode_geometry{i}.sphere.center = [cos(theta(i)) sin(theta(i)) 0.5];
2024                 electrode_geometry{i}.sphere.radius = 0.1;
2025             end
2026             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
2027        case 31
2028             n_sphere = 8;
2029             theta = linspace(0, 2*pi, n_sphere+1); theta(end) = [];
2030             for i = 1:n_sphere
2031                 body_geometry{i}.sphere.radius   = 0.2;
2032                 body_geometry{i}.sphere.center   = [0.65*cos(theta(i)) 0.65*sin(theta(i)) 0.5];
2033                 body_geometry{i}.max_edge_length = 0.025*(1 + rem(i,2));
2034                 body_geometry{i}.name            = sprintf('Sphere%d', i);
2035             end
2036             body_geometry{n_sphere+1}.cylinder.radius = 1;
2037             body_geometry{n_sphere+1}.name            = 'Tank';
2038             n_elect = 16;
2039             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
2040             for i = 1:n_elect
2041                 electrode_geometry{i}.sphere.center = [cos(theta(i)) sin(theta(i)) 0.5];
2042                 electrode_geometry{i}.sphere.radius = 0.1;
2043                 electrode_geometry{i}.max_edge_length = 0.025*(1 + rem(i,2));
2044             end
2045             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
2046        case 32
2047             body_geometry.cylinder = struct;
2048             n_elect = 16;
2049             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
2050             for i = 1:n_elect
2051                 electrode_geometry{i}.point = [cos(theta(i)) sin(theta(i)) 0.5];
2052             end
2053             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
2054        case 33
2055             body_geometry.cylinder = struct;
2056             n_elect = 16;
2057             theta = linspace(0, 2*pi, n_elect+1); theta(end) = [];
2058             for i = 1:n_elect
2059                 if (rem(i,2))
2060                     electrode_geometry{i}.point = [cos(theta(i)) sin(theta(i)) 0.5];
2061                     electrode_geometry{i}.name  = sprintf('Point_Electrode%d', ceil(i/2));
2062                 else
2063                     electrode_geometry{i}.sphere.center = [cos(theta(i)) sin(theta(i)) 0.5];
2064                     electrode_geometry{i}.sphere.radius = 0.1;
2065                     electrode_geometry{i}.name          = sprintf('Circular_Electrode%d', floor(i/2));
2066                 end
2067             end
2068             fmdl = ng_mk_geometric_models(body_geometry, electrode_geometry);
2069        case 34
2070             body_geometry.body_of_extrusion = struct;
2071             body_geometry.max_edge_length = 0.15;
2072             fmdl = ng_mk_geometric_models(body_geometry);
2073         case 35
2074             body_geometry.body_of_extrusion.path_points   = [0 0 0; 0.25 0 1; 0.25 0 2; 0.25 0 3; 0 0 4];
2075             body_geometry.body_of_extrusion.path_segments = [1 2; 2 3; 3 4; 4 5];
2076             body_geometry.max_edge_length = 0.15;
2077             fmdl = ng_mk_geometric_models(body_geometry);
2078        case 36
2079             n_points = 16;
2080             theta = linspace(0, 2*pi, n_points+1)'; theta(end) = [];
2081             body_geometry.body_of_extrusion.profile_points   = 0.2*(2 + [0.75*sin(theta) cos(theta)]);
2082             body_geometry.body_of_extrusion.profile_segments = [(1:n_points)' [(2:n_points) 1]'];
2083             n_points = 32;
2084             theta = linspace(0, 2*pi, n_points+1)'; theta(end) = [];
2085             body_geometry.body_of_extrusion.path_points   = 1*(2 + [sin(theta) 1.5*cos(theta) zeros(n_points, 1)]);
2086             body_geometry.body_of_extrusion.path_segments = [(1:n_points)' [(2:n_points) 1]'];
2087             body_geometry.body_of_extrusion.vector_d      = [0; 0; 1];
2088             body_geometry.max_edge_length = 0.15;
2089             fmdl = ng_mk_geometric_models(body_geometry);
2090         case 0; fmdl = 36; % Return maximum number of tests.
2091         otherwise;
2092             error('Invalid test number.')
2093     end