Description of fwd_solve
Home > eidors > solvers > fwd_solve.m
fwd_solve
PURPOSE
FWD_SOLVE: calculate data from a fwd_model object and an image
SYNOPSIS
function data = fwd_solve(fwd_model, img)
DESCRIPTION
 FWD_SOLVE: calculate data from a fwd_model object and an image
 fwd_solve can be called as
    data= fwd_solve( img)
 or (deprecated)
    data= fwd_solve( fwd_model, img)
 in each case it will call the fwd_model.solve
                        or img.fwd_model.solve method
 For reconstructions on dual meshes, the interpolation matrix
    is defined as fwd_model.coarse2fine. If required, this takes
    coarse2fine * x_coarse = x_fine
 data      is a measurement data structure
 fwd_model is a fwd_model structure
 img       is an img structure
 Options: (not available on all solvers)
    img.fwd_solve.get_all_meas = 1 (data.volt = all FEM nodes, but not CEM)
    img.fwd_solve.get_all_nodes= 1 (data.volt = all nodes, including CEM)
    img.fwd_solve.get_elec_curr= 1 (data.elec_curr = current on electrodes)
 Parameters:
    fwd_model.background = constant conductivity offset added to elem_data
    fwd_model.coarse2fine = linear mapping between img.elem_data and model parameters
    img.params_mapping = function mapping img.elem_data to model parameters
CROSS-REFERENCE INFORMATION
This function calls:
eidors_obj EIDORS_OBJ: maintains EIDORS internals
mdl_normalize MDL_NORMALIZE Check or set the normalize_measurements flag on a model.
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_image MK_IMAGE: create eidors image object
system_mat_higher_order Assemble the total stiffness matrix : s_mat.E=At;
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
eidors_cache EIDORS_CACHE Control eidors caching
eidors_default EIDORS_DEFAULT Default function handler.
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
ab_tv_diff_solve AB_TV_DIFF_SOLVE inverse solver for Andrea Borsic's
calc_noise_params params = GREIT_noise_params(imdl, homg_voltage, sig_voltage)
manchester_tomography Example to show reconstructions from
np_calc_jacobian NP_CALC_JACOBIAN: J= np_calc_jacobian(fwd_model, img)
np_fwd_solve NP_FWD_SOLVE: data= np_fwd_solve(fwd_model, img)
np_inv_solve NP_INV_SOLVE inverse solver for Nick Polydorides EIDORS3D code
cheating_2d code to simulate inverse crimes in EIT
compare_2d_algs Compare different 2D reconstructions
compare_3d_algs Compare different 3D reconstructions
demo_2d_simdata Example of using EIDORS to simulate 2D data and to
demo_3d_simdata How to make simulation data using EIDORS3D
demo_real [inhomg_img, demo_img] = demo_real;
eidors2d_demo1 EidorsDemo1 Demonstrates the use of 2D EIT Package with linear basis
ex_fwd2d_high_order ensure dev/m_crabb/forward_problem is on the path
ex_fwd3d_high_order Make common model, and make an image
resistor_model DEMO to show really simple application of EIDORS framework
mdl_slice_mapper MDL_SLICE_MAPPER: map pixels to FEM elements or nodes
show_3d_slices show_3d_slices(img, z_cuts, x_cuts, y_cuts, any_cuts)
show_current SHOW_CURRENT: show current or other quantity defined
show_pseudosection SHOW_PSEUDOSECTION: show a pseudo-section image of data
solve_volt_image SOLVE_VOLT_IMAGE: solve and create images of voltage
sigmatome2_filter SIGMATOME2_FILTER: Hardware filter and stim_patterns for Sigmatome II device
mat_idx_to_electrode MAT_IDX_TO_ELECTRODE: create electrodes from mat_idx values
GREIT3D_distribution GREIT3D_distribution: create target distributions for 3D GREIT
analytic_2d_circle V = analytic_2d_circle(J, [s_h, s_i, b, a, angl])
calc_elem_current calc_elem_current: calculate current vector in each FEM element
calc_model_reduction calc_model_reduction: calculate the fields for a reduced model
mk_GREIT_model MK_GREIT_MODEL: make EIDORS inverse models using the GREIT approach
mk_geophysics_model imdl = mk_geophysics_model(str, ne, [option])
mk_grid_model MK_GRID_MODEL: Create reconstruction model on pixelated grid
mono2stim MONO2SIM transform monopolar stimulation into another stim pattern
simulate_2d_movement SIMULATE_2D_MOVEMENT simulate rotational movement in 2D
simulate_3d_movement SIMULATE_3D_MOVEMENT simulate rotational movement in 3D
simulate_movement SIMULATE_MOVEMENT simulate small conductivity perturbations
solve_RM_2Dslice SOLVE_RM_2DSLICE: cut slices out of a 3D model
stim_meas_list STIM_MEAS_LIST: mk stimulation pattern from list of electrodes
test_GREIT_model
calc_meas_icov meas_icov = calc_meas_icov(inv_model)
calc_all_node_voltages CALC_ALL_NODE_VOLTAGES - calculate voltage on all nodes
calc_transferimpedance CALC_TRANSFERIMPEDANCE: Calculates transfer impedance matrix
eit_spice function spice = eit_spice(img, [name])
fwd_solve_2p5d_1st_order FWD_SOLVE_2P5D_1ST_ORDER: data= fwd_solve_2p5d_1st_order(img)
fwd_solve_apparent_resistivity fwd_solve_apparent_resistivity: fwd_solve output as apparent resistivity
fwd_solve_halfspace FWD_SOLVE_HALFSPACE: data = fwd_solve_halfspace(img)
fwd_solve_higher_order Solve for voltages (nodes/electrodes) for a forward model.
jacobian_adjoint JACOBIAN_ADJOINT: J= jacobian_adjoint(img)
jacobian_adjoint_2p5d_1st_order JACOBIAN_ADJOINT_2P5D: J= jacobian_adjoint_2p5d_1st_order(img)
jacobian_adjoint_higher_order Find the Jacobian associated with an image (and forward model)
jacobian_apparent_resistivity jacobian_apparent_resistivity: Jacobian output as apparent resistivity
jacobian_movement JACOBIAN_MOVEMENT Computes the Jacobian matrix for conductivity and
jacobian_movement_2p5d_1st_order JACOBIAN_MOVEMENT_2P5D: J = jacobian_movement_2p5d_1st_order(img)
jacobian_movement_halfspace JACOBIAN_MOVEMENT_PERTURB: J= jacobian_movement_perturb(img)
jacobian_movement_perturb JACOBIAN_MOVEMENT_PERTURB: J= jacobian_movement_perturb(img)
jacobian_perturb JACOBIAN_PERTURB: J= jacobian_perturb(fwd_model, img)
system_mat_1st_order SYSTEM_MAT_1ST_ORDER: SS= system_mat_1st_order(fwd_model, img)
system_mat_2p5d_1st_order SYSTEM_MAT_2P5D_1ST_ORDER: 2.5D system matrix
system_mat_fields SYSTEM_MAT_FIELDS: fields (elem to nodes) fraction of system mat
system_mat_instrument SYSTEM_MAT_INSTRUMENT:
fwd_solve FWD_SOLVE: calculate data from a fwd_model object and an image
GREIT_desired_img_FEMmesh GREIT_DESIRED_IMG_FEMmesh GREIT onto a FEM mesh
calc_noise_figure CALC_NOISE_FIGURE: calculate the noise amplification (NF) of an algorithm
calc_solution_error CALC_SOLUTION_ERROR Calculate residuals for a solution
inv_solve_TSVD INV_SOLVE_TSVD: inverse solver based on truncatated SVD
inv_solve_TV_pdipm INV_SOLVE_TV_PDIPM inverse solver for Andrea Borsic's
inv_solve_abs_GN_constrain Do Gauss Netwon Method with barrier to ensure positvity of the con
inv_solve_abs_GN_prior INV_SOLVE_ABS_GN_PRIOR inverse solver (WITH DIFFERENT PRIOR AT ITERATION!!!!!)
inv_solve_abs_annealingMetropolis_params INV_SOLVE_ABS_ANNEALINGSIMPLEX_PARAMS absolute solver using the simplex annealing method.
inv_solve_abs_annealingSimplex_params INV_SOLVE_ABS_ANNEALINGSIMPLEX_PARAMS absolute solver using the simplex annealing method.
inv_solve_abs_pdipm INV_SOLVE_ABS_PDIPM inverse solver for absolute data using Primal/Dual interior point method
inv_solve_cg function img= inv_solve_cg(inv_model, data1);
inv_solve_conj_grad INV_SOLVE_CONJ_GRAD inverse solver based on the CG
inv_solve_core INV_SOLVE_CORE Solver using a generic iterative algorithm
inv_solve_gn function img= inv_solve_gn(inv_model, data1);
line_optimize LINE_OPTIMIZE Cheap line optimizer
primaldual_tvrecon_lsearch [rs,x]=primaldual_tvrecon_lsearch(inv_mdl, vmeas, ...
calc_data_prior_test Verify dataprior:
calc_jacobian_test Verify Jacobian Calculation by small derivative from forward problem
demo_real_test2 Perform tests based on the demo_real function with new structs
demo_real_test3 Perform tests based on the demo_real function with new structs
perturb_jacobian_test Perturbation Jacobians
test_2d_resistor Create 2D model of a cylindrical resistor
test_3d_resistor Create 3D model of a Rectangular resistor
test_colour_direction Test colour mapping
test_performance TEST_PERFORMANCE: test of difference reconstruction algorithms
test_performance_img TEST_PERFORMANCE: test of difference reconstruction algorithms
SUBFUNCTIONS
function mdl = prepare_model(mdl)
function do_unit_test
SOURCE CODE
function data = fwd_solve(fwd_model, img)
% FWD_SOLVE: calculate data from a fwd_model object and an image
%
% fwd_solve can be called as
%    data= fwd_solve(img)
% or (deprecated)
%    data= fwd_solve(fwd_model, img)
%
% in each case it will call the fwd_model.solve
%                        or img.fwd_model.solve method
%
% For reconstructions on dual meshes, the interpolation matrix
%    is defined as fwd_model.coarse2fine. If required, this takes
%    coarse2fine * x_coarse = x_fine
%
% data      is a measurement data structure
% fwd_model is a fwd_model structure
% img       is an img structure
%
% Options: (not available on all solvers)
%    img.fwd_solve.get_all_meas = 1 (data.volt = all FEM nodes, but not CEM)
%    img.fwd_solve.get_all_nodes= 1 (data.volt = all nodes, including CEM)
%    img.fwd_solve.get_elec_curr= 1 (data.elec_curr = current on electrodes)
%
% Parameters:
%    fwd_model.background = constant conductivity offset added to elem_data
%    fwd_model.coarse2fine = linear mapping between img.elem_data and model parameters
%    img.params_mapping = function mapping img.elem_data to model parameters
%
% (C) 2005 Andy Adler. License: GPL version 2 or version 3
% $Id: fwd_solve.m 6307 2022-04-20 17:45:43Z aadler $
if ischar(fwd_model) && strcmp(fwd_model,'UNIT_TEST'); do_unit_test; return; end
if nargin == 1
   img= fwd_model;
else
   warning('EIDORS:DeprecatedInterface', ...
      ['Calling FWD_SOLVE with two arguments is deprecated and will cause' ...
       ' an error in a future version. First argument ignored.']);
end
ws = warning('query','EIDORS:DeprecatedInterface');
warning off EIDORS:DeprecatedInterface
fwd_model= img.fwd_model;
fwd_model= prepare_model(fwd_model);
% TODO: This should be handled by the data_mapper
if isfield(img,'params_mapping')
%     fwd_model data is provided using a mapping function
    mapping_function= img.params_mapping.function;
    img= feval(mapping_function,img);
end
if isfield(fwd_model,'coarse2fine') && isfield(img,'elem_data')
   c2f= fwd_model.coarse2fine;
   if size(img.elem_data,1)==size(c2f,2)
%     fwd_model data is provided on coarse mesh
      img.elem_data = c2f * img.elem_data;
      if isfield(fwd_model,'background')
          img.elem_data = img.elem_data + fwd_model.background;
      end
   end
end
if ~isfield(fwd_model, 'electrode')
   error('EIDORS: attempting to solve on model without electrodes');
end
if ~isfield(fwd_model, 'stimulation')
   error('EIDORS: attempting to solve on model without stimulation patterns');
end
solver = fwd_model.solve;
if ischar(solver)
    solver = str2func(solver);
end
copt.fstr = 'fwd_solve';
n_frames = size(img.elem_data,2);
for frame = 1:n_frames;
   imgn = img; imgn.elem_data = imgn.elem_data(:,frame,:,:);
   copt.cache_obj = imgn;
   copt.boost_priority = -2; % fmdl evaluations are low priority
   tmp = eidors_cache(solver, {imgn}, copt);
   data(frame) = eidors_obj('data',tmp);  % create data object
end
if isa(fwd_model.solve,'function_handle')
    solver = func2str(fwd_model.solve);
else
    solver = fwd_model.solve;
end
if strcmp(solver,'eidors_default');
    solver = eidors_default('get','fwd_solve');
end
if isfield(fwd_model,'measured_quantity') && ~isfield(data,'measured_quantity')
   warning('EIDORS:MeasurementQuantityObliviousSolver',...
      ['The solver %s did not handle the requested measurement quantity properly.\n'...
       'The results may be incorrect. Please check the code to verify.'], ...
       solver);
elseif isfield(fwd_model,'measured_quantity') ...
        && isfield(data,'measured_quantity') ...
        && ~strcmp(fwd_model.measured_quantity, data.measured_quantity)
   error('EIDORS:MeasurementQuantityDisagreement',...
       'The solver %s return measurements as %s, while %s was expected.',...
       solver, data.measured_quantity, fwd_model.measured_quantity);
end
warning on EIDORS:DeprecatedInterface
function mdl = prepare_model(mdl)
mdl = mdl_normalize(mdl,mdl_normalize(mdl));
if ~isfield(mdl,'elems');
    return;
end
mdl.elems  = double(mdl.elems);
mdl.n_elem = size(mdl.elems,1);
mdl.n_node = size(mdl.nodes,1);
if isfield(mdl,'electrode');
    mdl.n_elec = length(mdl.electrode);
else
    mdl.n_elec = 0;
end
function do_unit_test
img = mk_image(mk_common_model('a2c2',4));
% TODO Try other solvers
img.elem_data([1,5,9,10]) = 2;
A = [1,-1,0,0]; a=A.';
B = [0,0,1,-1]; b=B.';
G = 2;
P = exp(0.1j);
for solv = 1:4; switch solv
    case 1; solver = 'fwd_solve_1st_order';
    case 2; solver = 'fwd_solve_2p5d_1st_order';
    case 3; solver = 'fwd_solve_higher_order';
            img.fwd_model.system_mat = @system_mat_higher_order;
            img.fwd_model.approx_type = 'tri3';
    case 4; break;
    end
    for test = 1:4; switch test
       case 1; str='reciprocity';
               mPat = {A,B}; sPat = {b,a};
       case 2; str='Gain';
               mPat = {A,A*G}; sPat = {b,b/G};
       case 3; str='Phase';
               mPat = {A,A*P}; sPat = {b,b*P};
       case 4; break
       end
       img.fwd_model.solve = solver;
       img.fwd_model.stimulation  = struct( ...
          'meas_pattern', mPat, 'stim_pattern', sPat );
        vv= getfield(fwd_solve(img),'meas');
        unit_test_cmp([solver,':',str],diff(vv),0,10*eps)
    end
end