Description of get_elem_volume
Home > eidors > models > get_elem_volume.m
get_elem_volume
PURPOSE
GET_ELEM_VOLUME: VOL = get_elem_volume(fwd_model, map_node)
SYNOPSIS
function VOL = get_elem_volume(fwd_model, map_node)
DESCRIPTION
 GET_ELEM_VOLUME: VOL = get_elem_volume(fwd_model, map_node )
 Calculate volume (or area) of each element in model
 If the model has a 'coarse2fine' element, then the
 returned VOL applies to the coarse matrix (unless map_node <0)
 if map_node < 0 or map_node=='no_c2f', do not apply coarse2fine (if it exists)
 if abs(map_node) == 1, then calculated volumes are the volume fraction for each node
 BUGS: can't currently apply coarse2fine on map_node.
CROSS-REFERENCE INFORMATION
This function calls:
get_elem_volume GET_ELEM_VOLUME: VOL = get_elem_volume(fwd_model, map_node)
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_image MK_IMAGE: create eidors image object
num_elems NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
num_nodes NUM_NODES: number of elemnts in a (fwd or inv model or image)
sparse SPARSE Create sparse matrix (EIDORS overload).
eidors_cache EIDORS_CACHE Control eidors caching
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
calc_noise_params params = GREIT_noise_params(imdl, homg_voltage, sig_voltage)
dm_mk_fwd_model DM_MK_FWD_MODEL: create a fwd_model object using distmesh
mat_idx_to_electrode MAT_IDX_TO_ELECTRODE: create electrodes from mat_idx values
analytic_2d_circle V = analytic_2d_circle(J, [s_h, s_i, b, a, angl])
check_c2f_quality CHECK_C2F_QUALITY Check the coarse2fine mapping between two models
fix_model FIX_MODEL: Add useful fields to a model
get_elem_volume GET_ELEM_VOLUME: VOL = get_elem_volume(fwd_model, map_node)
mk_analytic_c2f MK_ANALYTIC_C2F: create a mapping matrix from coarse to fine FEM
mk_c2f_circ_mapping MK_C2F_CIRC_MAPPING: create a mapping matrix from circles/spheres to FEM
mk_grid_c2f MK_GRID_C2F - calculate a coarse2fine mapping for grid coarse models.
mk_tet_c2f MK_TET_C2F - calculate a coarse2fine mapping for two tet-based models.
mk_tri2tet_c2f MK_TRI2TET_C2F - coarse2fine mapping between tri-based and tet-based models
mk_tri_c2f MK_TRI_C2F - calculate a coarse2fine mapping for triangle-based models.
GREIT_desired_img_sigmoid GREIT_DESIRED_IMG_SIGMOID sigmoid-decay desired image function for GREIT
calc_image_SNR % CALC_IMAGE_SNR: Calculates the signal-to-noise ratio (SNR) in the image
calc_noise_figure CALC_NOISE_FIGURE: calculate the noise amplification (NF) of an algorithm
prior_gaussian_HPF PRIOR_GAUSSIAN_HPF calculate image prior
test_performance TEST_PERFORMANCE: test of difference reconstruction algorithms
test_performance_img TEST_PERFORMANCE: test of difference reconstruction algorithms
SUBFUNCTIONS
function VOL = calc_volume(NODE,ELEM)
function do_unit_test
SOURCE CODE
function VOL = get_elem_volume(fwd_model, map_node)
% GET_ELEM_VOLUME: VOL = get_elem_volume(fwd_model, map_node)
% Calculate volume (or area) of each element in model
%
% If the model has a 'coarse2fine' element, then the
% returned VOL applies to the coarse matrix (unless map_node <0)
%
% if map_node < 0 or map_node=='no_c2f', do not apply coarse2fine (if it exists)
%
% if abs(map_node) == 1, then calculated volumes are the volume fraction for each node
% BUGS: can't currently apply coarse2fine on map_node.
% (C) 2009 Andy Adler. License: GPL version 2 or version 3
% $Id: get_elem_volume.m 6157 2021-11-02 13:02:02Z aadler $
if ischar(fwd_model) && strcmp(fwd_model,'UNIT_TEST'); do_unit_test; return; end
% If it looks like a fwd model
if ~isfield(fwd_model,'type');
  if isfield(fwd_model,'nodes') && isfield(fwd_model,'elems')
     fwd_model.type = 'fwd_model';
  end
end
switch fwd_model.type
  case 'fwd_model'; % do nothing, we're ok
  case 'rec_model'; % do nothing, we're ok
  case 'inv_model'; fwd_model = fwd_model.fwd_model;
  case 'image';     fwd_model = fwd_model.fwd_model;
  otherwise;
     error('get_elem_volume: expecting fwd_model, got %s', ...
           fwd_model.type)
end
if nargin==1; map_node= 0; end
if ischar(map_node) && strcmp(map_node,'no_c2f'); map_node=-inf; end
% calculate element volume and surface area
NODE = fwd_model.nodes';
ELEM = fwd_model.elems';
copt.cache_obj = {NODE, ELEM,map_node};
copt.fstr = 'elem_volume';
copt.boost_priority = -4;
VOL = eidors_cache(@calc_volume, {NODE, ELEM}, copt);
if isfield(fwd_model,'coarse2fine') && map_node>=0
   VOL= fwd_model.coarse2fine' * VOL;
end
% Calculate the mapping of each element onto the associated node
% Map(i,j) = 1/Ne if elem j has node i
if abs(map_node)==1
   [d,e]= size(ELEM);
   map = sparse( ELEM, ones(d,1)*(1:e), 1/d, size(NODE,2),e);
   VOL = map * VOL;
end
function VOL = calc_volume(NODE,ELEM)
    [d,e]= size(ELEM);
    VOL=zeros(e,1);
    ones_d = ones(1,d);
    d1fac = prod( 1:d-1 );
    if d > size(NODE,1)
        for i=1:e
            this_elem = NODE(:,ELEM(:,i));
            VOL(i)= abs(det([ones_d;this_elem])) / d1fac;
        end
    elseif d == 3 % 3D nodes in 2D mesh
        for i=1:e
            this_elem = NODE(:,ELEM(:,i));
            d12= det([ones_d;this_elem([1,2],:)])^2;
            d13= det([ones_d;this_elem([1,3],:)])^2;
            d23= det([ones_d;this_elem([2,3],:)])^2;
            VOL(i)= sqrt(d12 + d13 + d23 ) / d1fac;
        end
    elseif d == 2 % 3D nodes in 1D mesh (ie resistor mesh)
        for i=1:e
            this_elem = NODE(:,ELEM(:,i));
            d12= det([ones_d;this_elem([1],:)])^2;
            d13= det([ones_d;this_elem([2],:)])^2;
            d23= det([ones_d;this_elem([3],:)])^2;
            VOL(i)= sqrt(d12 + d13 + d23 ) / d1fac;
        end
    else
        error('mesh size not understood when calculating volumes')
    end
function do_unit_test
  imdl = mk_common_model('a2c2',8);
  tt = 0.03125*ones(4,1);
  out = get_elem_volume(imdl.fwd_model);
  unit_test_cmp('fmdl:',  out(1:4), tt, 1e-10);
  out = get_elem_volume(imdl);
  unit_test_cmp('imdl:',  out(1:4), tt, 1e-10);
  out = get_elem_volume(mk_image(imdl,1));
  unit_test_cmp('image:', out(1:4), tt, 1e-10);
  fmdl = imdl.fwd_model;
  unit_test_cmp('fmdl (size 1):',  size(out,1), [num_elems(fmdl)]);
  out0= get_elem_volume(fmdl,0);
  unit_test_cmp('fmdl (size 1):',  size(out0,1), [num_elems(fmdl)]);
  out1= get_elem_volume(fmdl,1);
  unit_test_cmp('fmdl (size 1):',  size(out1,1),[num_nodes(fmdl)]);
  unit_test_cmp('fmdl (nodes 1):',  sum(out), sum(out1), 1e-10);
  ttn(1) = 0.041666666666667; ttn(2:5) = 0.088388347648318;
  unit_test_cmp('fmdl (nodes 2):',  out1(1:5), ttn(:), 1e-10);
  fmdl.coarse2fine = zeros(num_elems(fmdl),2);
  fmdl.coarse2fine(1:4,1) = 1;
  fmdl.coarse2fine(5:end,2) = 1;
  outc= get_elem_volume(fmdl,-2); % don't use
  unit_test_cmp('fmdl (c2f 1):',  out0, outc);
  outc= get_elem_volume(fmdl,0); % use c2f
  unit_test_cmp('fmdl (c2f 2):',  outc(1), sum(tt), 1e-10);
  unit_test_cmp('fmdl (c2f 3):',  sum(outc), sum(out0), 1e-10);
  unit_test_cmp('fmdl (c2f 4):',  size(outc), [2,1]);
  outc= get_elem_volume(fmdl,-1); % use c2f and map_node
  unit_test_cmp('fmdl (nodes 2):',  outc(1:5), ttn(:), 1e-10);