Description of remove_unused_nodes
Home > eidors > models > remove_unused_nodes.m
remove_unused_nodes
PURPOSE
REMOVE_UNUSED_NODES: identify and remove unused nodes in model
SYNOPSIS
function fmdl = remove_unused_nodes(fmdl);
DESCRIPTION
 REMOVE_UNUSED_NODES: identify and remove unused nodes in model
 Usage: fmdl = remove_unused_nodes( fmdl );
CROSS-REFERENCE INFORMATION
This function calls:
eidors_msg EIDORS_MSG eidors progress and status messages
mk_common_model MK_COMMON_MODEL: make common EIT models
num_elems NUM_ELEMS: number of elemnts in a (fwd or inv model or image)
num_nodes NUM_NODES: number of elemnts in a (fwd or inv model or image)
remove_unused_nodes REMOVE_UNUSED_NODES: identify and remove unused nodes in model
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
mat_idx_to_electrode MAT_IDX_TO_ELECTRODE: create electrodes from mat_idx values
remove_unused_nodes REMOVE_UNUSED_NODES: identify and remove unused nodes in model
SUBFUNCTIONS
function mat = remap(nidx,mat)
function fmdl = assign_new_gnd_node(fmdl);
function do_unit_test
SOURCE CODE
function fmdl = remove_unused_nodes(fmdl);
% REMOVE_UNUSED_NODES: identify and remove unused nodes in model
% Usage: fmdl = remove_unused_nodes(fmdl);
% (C) 2019 Andy Adler. License: GPL v2 or v3. $Id: remove_unused_nodes.m 6101 2021-03-30 18:52:30Z aadler $
   if ischar(fmdl) && strcmp(fmdl,'UNIT_TEST'); do_unit_test; return; end
   if num_elems(fmdl)==0; return; end; % don't operate on pathalogical models
   usednodes = unique(fmdl.elems(:));
   if max(usednodes) > num_nodes(fmdl)
      error('remove_unused_nodes: more nodes are used than exist');
   end
   fmdl0 = fmdl;
   nidx = zeros(num_nodes(fmdl),1);
   nidx(usednodes) = 1:length(usednodes);
   fmdl.nodes(nidx==0,:) = [];
   fmdl.elems = remap(nidx, fmdl.elems);
   for i=1:length(fmdl.electrode)
      fmdl.electrode(i).nodes =  remap(nidx, fmdl.electrode(i).nodes);
      removed = fmdl.electrode(i).nodes == 0;
      fmdl.electrode(i).nodes( removed ) = [];
      elec_empty = isempty(fmdl.electrode(i).nodes);
      if isfield(fmdl.electrode(i),'faces')
          fmdl.electrode(i).faces =  remap(nidx, fmdl.electrode(i).faces);
          removed = any(fmdl.electrode(i).faces== 0,2);
          fmdl.electrode(i).faces(removed,:) = [];
          elec_empty= elec_empty && isempty(fmdl.electrode(i).faces);
      end
      if elec_empty
         eidors_msg('Zeros in electrode #%d nodes and faces. Often this means parts of the model are disconnected.',i,1);
         keyboard
      end
   end
%  fmdl.boundary = find_boundary(fmdl);
   fmdl.boundary = remap(nidx, fmdl.boundary);
   fmdl.boundary(any(fmdl.boundary==0,2),:) = [];
   fmdl.gnd_node = nidx(fmdl.gnd_node);
   if fmdl.gnd_node == 0 %% New gnd node if missing
      fmdl = assign_new_gnd_node( fmdl );
   end
%  fmdl.elems = reshape(nidx(fmdl.elems),[],size(fmdl.elems,2));
function mat = remap(nidx,mat)
   mat = reshape(nidx(mat),size(mat));
function fmdl = assign_new_gnd_node(fmdl);
   eidors_msg('FEM_ELECTRODE: Lost ground node => replacing',1);
   d2 = sum((fmdl.nodes - repmat(mean(fmdl.nodes, 1), size(fmdl.nodes, 1), 1)).^2,2);
   [~,fmdl.gnd_node] = min(d2);
function do_unit_test
   fmdl = getfield(mk_common_model('a2c2',4),'fwd_model');
   fmdl.elems(1:4,:) = [];
   fmdl = remove_unused_nodes(fmdl);
   unit_test_cmp('nodes',size(fmdl.nodes),[40,2]);
   unit_test_cmp('elems',size(fmdl.elems),[60,3]);
   unit_test_cmp('ground',fmdl.gnd_node,3);