Description of left_divide
Home > eidors > algorithms > left_divide.m
left_divide
PURPOSE
[V] = LEFT_DIVIDE(E,I,tol,pp,V);
SYNOPSIS
function [V] = left_divide(E,I,tol,~,V)
DESCRIPTION
[V] = LEFT_DIVIDE(E,I,tol,pp,V);
[V] = LEFT_DIVIDE(E,I,fmdl)
 Implements left division for symmetric positive definite system solves
 such as the sparse forward solve and dense solve for a GN descent
 direction. LEFT_DIVIDE is optimised for symmetric matrices and overcomes
 small inefficiencies of matlab's mldivide. For non-symmetric solves
 please use mldivide.
 Also uses conjugate gradients (for large problems).
 E   = The full rank system matrix
 I   = The currents matrix (RHS)
 tol = The tolerance in the forward solution, e.g. 1e-5
 pp,V are old options from previous solver. tilde used in arguments list
 to ignore pp and keep matlab's code analyzer happy
CROSS-REFERENCE INFORMATION
This function calls:
left_divide [V] = LEFT_DIVIDE(E,I,tol,pp,V);
eidors_msg EIDORS_MSG eidors progress and status messages
eidors_obj EIDORS_OBJ: maintains EIDORS internals
mk_circ_tank MK_CIRC_TANK: make a cylindrical tank FEM geometry in 2D or 3D
mk_common_model MK_COMMON_MODEL: make common EIT models
mk_image MK_IMAGE: create eidors image object
mk_stim_patterns MK_STIM_PATTERNS: create an EIDORS stimulation pattern structure
stim_meas_list STIM_MEAS_LIST: mk stimulation pattern from list of electrodes
sparse SPARSE Create sparse matrix (EIDORS overload).
calc_RtR_prior RtR = calc_RtR_prior(inv_model)
calc_hyperparameter CALC_HYPERPARAMETER: calculate hyperparameter value
calc_jacobian CALC_JACOBIAN: calculate jacobian from an inv_model
calc_meas_icov meas_icov = calc_meas_icov(inv_model)
calc_system_mat CALC_SYSTEM_MAT: calculate FEM system matrix from fwd_model and image
fwd_model_parameters FWD_MODEL_PARAMETERS: data= fwd_solve_1st_order(fwd_model, image)
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
inv_solve INV_SOLVE: calculate imag from an inv_model and data
eidors_default EIDORS_DEFAULT Default function handler.
unit_test_cmp UNIT_TEST_CMP: compare matrices in eidors output
This function is called by:
left_divide [V] = LEFT_DIVIDE(E,I,tol,pp,V);
demo_complex This demo function shows how the EIT problem can be formulated in a complex
eidors2d_demo1 EidorsDemo1 Demonstrates the use of 2D EIT Package with linear basis
fwd_solve_1st_order FWD_SOLVE_1ST_ORDER: data= fwd_solve_1st_order(img)
fwd_solve_2p5d_1st_order FWD_SOLVE_2P5D_1ST_ORDER: data= fwd_solve_2p5d_1st_order(img)
fwd_solve_higher_order Solve for voltages (nodes/electrodes) for a forward model.
jacobian_adjoint JACOBIAN_ADJOINT: J= jacobian_adjoint(img)
jacobian_adjoint_2p5d_1st_order JACOBIAN_ADJOINT_2P5D: J= jacobian_adjoint_2p5d_1st_order(img)
jacobian_adjoint_higher_order Find the Jacobian associated with an image (and forward model)
jacobian_elem2nodes JACOBIAN_ELEM2NODES: calculate Jacobian on Nodes from Elem solver
jacobian_movement_2p5d_1st_order JACOBIAN_MOVEMENT_2P5D: J = jacobian_movement_2p5d_1st_order(img)
calc_error_norms_for_square_domain Get forward model of the img and the conductivity per element
calc_GREIT_RM CALCULATE GREIT reconstruction matrix
inv_solve_core INV_SOLVE_CORE Solver using a generic iterative algorithm
inv_solve_diff_GN_one_step INV_SOLVE_DIFF_GN_ONE_STEP inverse solver using approach of Adler&Guardo 1996
SUBFUNCTIONS
function V= non_iterative(E,I);
function V=iterative_solve(E,I,tol,V,fmdl)
function do_unit_test
function do_timing_unit_tests
SOURCE CODE
function [V] = left_divide(E,I,tol,~,V)
%[V] = LEFT_DIVIDE(E,I,tol,pp,V);
%[V] = LEFT_DIVIDE(E,I,fmdl)
%
% Implements left division for symmetric positive definite system solves
% such as the sparse forward solve and dense solve for a GN descent
% direction. LEFT_DIVIDE is optimised for symmetric matrices and overcomes
% small inefficiencies of matlab's mldivide. For non-symmetric solves
% please use mldivide.
%
% Also uses conjugate gradients (for large problems).
%
% E   = The full rank system matrix
% I   = The currents matrix (RHS)
% tol = The tolerance in the forward solution, e.g. 1e-5
%
% pp,V are old options from previous solver. tilde used in arguments list
% to ignore pp and keep matlab's code analyzer happy
% (c) N. Polydorides 2003 % Copying permitted under terms of GNU GPL
% $Id: left_divide.m 6442 2022-12-02 00:37:28Z aadler $
if ischar(E) && strcmp(E,'UNIT_TEST'); do_unit_test; return; end
if nargin<3;
   tol=1e-8;
end
do_pcg = false;
if isstruct(tol);
   fmdl = tol;
   try
      do_pcg = fmdl.left_divide.do_pcg;
   catch
   end
   try
      tol = fmdl.left_divide.tol;
   catch
      tol = 1e-8;
   end
   try
      V = fmdl.left_divide.V_initial;
   catch
      sz= [size(E),size(I)];
      V = eidors_obj('get-cache', sz, 'left_divide_V');
      if isempty(V); V = zeros(size(E,1),size(I,2)); end
   end
end
if ~do_pcg
   try
     V= non_iterative(E,I);
   catch excp
       % TODO: check if this catch block is needed
       if ~strcmp(excp.identifier , 'MATLAB:nomem')
           rethrow(excp); % rethrow error
       end
       eidors_msg('Memory exhausted for inverse. Trying PCG',2);
       V=iterative_solve(E,I,tol,V,fmdl);
   end
else
   V=iterative_solve(E,I,tol,V,fmdl);
end
function V= non_iterative(E,I);
    % V= E\I;
    % This takes MUCH longer when you have  more vectors in I,
    %  even if they are repeated. There must be some way to simplify
    %  this to speed it up. Matlab's sparse operators really should
    %  do this for you.
    % TODO:
    % 1. change from QR implementation to basis implementation
    % 2. implement selection for required nodal values
    % 3. cache basis solve
    % 4. possibly change to itterative for successive solves on the same
    %    mesh
    if issparse(E)
        inotzeros = logical(any(I,2));
        % Don't need to cache, this is fast
        [Qi,R] = qr(I(inotzeros,:),0);
        rnotzeros = logical(any(R,2));
        % Bug in octave sparse for v6.4
        % Not needed for v7.3
        % if exist('OCTAVE_VERSION')
        %    rnotzeros = full(rnotzeros);
        % end
        R= R(rnotzeros,:);
        Q = zeros(size(I,1), size(R,1)); % Faster if not sparse
        Q(inotzeros,:) = Qi(:,rnotzeros);
        %disp([size(I), size(Qi), size(R)])
%        [Q,R] = qr(I,0);
%        rnotzeros = any(R~=0,2);
%        Q= Q(:,rnotzeros);
%        R= R(rnotzeros,:);
        V= (E \ Q)*R;
    else
        if isreal(E)
            try
                % for dense solve of tikhonov regularised least squares
                % matrix E is symmetric if it is of the form
                % (J.'*W*J + hp^2*R.'R) and is real
                opts.SYM=true;
                opts.POSDEF=true;
                V= linsolve(E,I,opts);
            catch Mexcp
                % error handling
                if(strcmp(Mexcp.identifier,'MATLAB:posdef'))
                    warning('EIDORS:leftDivideSymmetry',...
                        ['left_divide is optimised for symmetric ',...
                        'positive definite matrices.']);
                else
                    warning(['Error with linsolve in left_divide, trying backslash.\n',...
                        'Error identifier: ',Mexcp.identifier]);
                end
                % continue solve with backslash
                V=E\I;
            end
        else
            % cholesky only works for real valued system matrices
            V=E\I;
        end
    end
    % TODO: Iteratively refine
    %  From GH Scott: "once we have
    %   computed the approximate solution x, we perform one step
    %   of iterative refinement by computing the residual: r = Ax - b
    %   and then recalling the solve routine to solve
    %   Adx = r for the correction dx.
    % However, we don't want to repeat the '\', so we implement
    %   the underlying algorithm:
    %   If A is sparse, then MATLAB software uses CHOLMOD (after 7.2) to compute X.
    %    The computations result in  P'*A*P = R'*R
    %   where P is a permutation matrix generated by amd, and R is
    %   an upper triangular matrix. In this case, X = P*(R\(R'\(P'*B)))
    %
    % See also:
    % http://www.cs.berkeley.edu/~wkahan/MxMulEps.pdf
    % especially page 15 where it discusses the value of iterative refinement
    %  without extra precision bits.  ALso, we need to enable
function V=iterative_solve(E,I,tol,V,fmdl)
    [n_nodes,n_stims] = size(I);
    if isreal(E)
        opts.droptol = tol*100;
        opts.type = 'ict';
        U = ichol(E, opts);
        L = U';
        cgsolver = @pcg;
    else %Complex
        opts.droptol = tol/10;
        [L,U] = ilu(E, opts);
        cgsolver = @bicgstab;
    end
    for i=1:n_stims
        [V(:,i),~] = feval( cgsolver, E,I(:,i), ...
            tol*norm(I(:,i)),n_nodes,L,U,V(:,i));
    end
    sz= [size(E),size(I)];
    eidors_obj('set-cache', sz, 'left_divide_V', V);
% Test code
function do_unit_test
%do_timing_unit_tests; return
% test solvers are unaffected
inv_solve('UNIT_TEST')
fwd_solve_1st_order('UNIT_TEST')
% test non-symmetric handling
s=warning('QUERY','EIDORS:leftDivideSymmetry');
warning('OFF','EIDORS:leftDivideSymmetry')
lastwarn('')
A=rand(1e3);
b=rand(1e3);
left_divide(A,b);
[~, LASTID] = lastwarn;
unit_test_cmp('sym warn',LASTID,'EIDORS:leftDivideSymmetry')
warning(s);
% test dense sym posdef solve
imdl=mk_common_model('n3r2',[16,2]);
img=mk_image(imdl,1);
img.elem_data=1+0.1*rand(size(img.elem_data));
J   = calc_jacobian(img);
RtR = calc_RtR_prior(imdl);
W   = calc_meas_icov(imdl);
hp  = calc_hyperparameter(imdl);
LHS = (J'*W*J +  hp^2*RtR);
RHS = J'*W;
unit_test_cmp('dense chol',LHS\RHS,left_divide(LHS,RHS),1e-13)
function do_timing_unit_tests
% The point of these tests are to verify which
%  matrices should be sparse and which full.
% Conclusion is that Q should be full - AA (jun 2022)
%eidors_cache off
Nel = 64;
for mn = 1:4; switch mn
    case 1;
        fmdl = mk_common_model('d2c0',64);
        fmdl = fmdl.fwd_model;
    case 2;
        fmdl = mk_common_model('l2c0',64);
        fmdl = fmdl.fwd_model;
    case 3;
        fmdl = mk_circ_tank(16, linspace(-1,1,41), {'planes',Nel, 21});
        fmdl.solve = @eidors_default;
        fmdl.system_mat = @eidors_default;
    case 4;
        fmdl = mk_circ_tank(32, linspace(-1,1,41), {'planes',Nel, 21});
        fmdl.solve = @eidors_default;
        fmdl.system_mat = @eidors_default;
    end
    stim= mk_stim_patterns(Nel,1,[0,3],[0,3],{},1);
    for sp = 1:2; switch sp;
       case 1;
           fmdl.stimulation = stim;
       case 2;
            SSMM = stim_meas_list(stim);
            [~,idx] = sort(rand(size(SSMM,1),1));
            fmdl.stimulation = stim_meas_list(SSMM(idx,:));
        end;
        img = mk_image(fmdl,1);
%       fwd_solve(img);
        s_mat = calc_system_mat(img);
        idx= 1:size(s_mat.E,1);
        idx(img.fwd_model.gnd_node) = [];
        E = s_mat.E(idx,idx);
        pp= fwd_model_parameters( img.fwd_model, 'skip_VOLUME' );
        I = pp.QQ(idx,:);
        inotzeros = logical(any(I,2));
        [Qi,R] = qr(I(inotzeros,:),0);
        rnotzeros = logical(any(R,2));
        R= R(rnotzeros,:);
        Q = sparse(size(I,1), size(R,1));
        Q(inotzeros,:) = Qi(:,rnotzeros);
        t=[];
        tic; T = E \ Q; t(end+1) = toc;
        tic; V = T * R; t(end+1) = toc;
        tic; T = full(E \ Q); t(end+1) = toc;
        tic; V = T * R; t(end+1) = toc;
        tic; T = E \ full(Q); t(end+1) = toc;
        tic; V = T * R; t(end+1) = toc;
        disp(t)
    end
end